-- ┌─────────────────────────────────────────────────────────────────────┐
-- │  Project:Tezca — Hyprland entry point (Lua)                          │
-- │  "Smoking mirror": obsidian black, glass, turquoise/jade accent.     │
-- │                                                                       │
-- │  This file only LOADS modular fragments in conf.d/ (DESIGN.md §5).    │
-- │  Edit the fragment, not this file. Order matters.                     │
-- └─────────────────────────────────────────────────────────────────────┘
--
-- WHY LUA
--
-- Hyprland 0.55 deprecated hyprlang (the `.conf` format) in favour of Lua, and
-- upstream will drop it entirely a release or two later; new config features
-- already land in Lua only. The previous hyprland.conf and its conf.d/*.conf
-- fragments are still in the repo, unloaded, as a rollback: rename this file to
-- hyprland.lua.off and relog to get the hyprlang path back. Hyprland picks the
-- format ONCE at startup — if hyprland.lua exists it wins, and `hyprctl reload`
-- cannot switch between them.
--
-- Launched via uwsm — environment lives in ~/.config/uwsm/{env,env-hyprland},
-- NOT here. Do not add `hl.env(...)` calls below; put them in uwsm/env.

local CONFIG = os.getenv("XDG_CONFIG_HOME")
if CONFIG == nil or CONFIG == "" then
    CONFIG = (os.getenv("HOME") or "") .. "/.config"
end

-- Fragments are addressed as bare module names (`require("input")`), not as
-- "conf.d.input": Lua translates dots in a module name to path separators, so
-- the literal `conf.d` directory can only be reached by putting it on the
-- search path itself.
package.path = CONFIG .. "/hypr/conf.d/?.lua;" .. package.path

local util = require("util")

require("nvidia")
require("monitors")
require("input")
require("decoration")
require("animations")
require("windowrules")
require("keybinds")

-- Your rebound keys, generated by `tezca keybind` / the Settings Keybinds page.
-- Loaded right after the shipped map so its unbind+bind pairs win. Lives outside
-- the repo, so rebinding a key never dirties the checkout. Created by
-- `tezca link`; safe to delete — you get the shipped keybindings back.
util.load(CONFIG .. "/tezca/keybinds.lua")

require("gaming")
require("ai")
require("autostart")

-- Hand-written machine-local overrides. Tezca never writes to this file, so it
-- is yours: put anything you don't want the tools to reformat here.
util.load(CONFIG .. "/hypr/conf.d/local.lua")

-- Generated machine-local overrides — what `tezca hypr set` / `tezca display set`
-- and the Settings sliders persist. Applied LAST, so it wins over everything.
-- Lives outside the repo so tuning a setting never dirties the checkout. Created
-- by `tezca link`; safe to delete — you get the shipped defaults back.
--
-- Unlike every require() above, this is DATA, not code: a flat table of dotted
-- config keys that `util.apply_overrides` validates key-by-key. A stale key from
-- a Hyprland upgrade gets dropped with a log line instead of erroring the config
-- and dumping you into emergency mode.
util.apply_overrides(util.load(CONFIG .. "/tezca/overrides.lua"))
