//! `tezca night` — blue-light filter (night light), over hyprsunset.
//!
//!   status [--machine]
//!   on | off | toggle
//!   temp <K>                  1000–6500; also switches it on
//!   schedule <HH:MM> <HH:MM>  | schedule off
//!   apply                     re-assert the saved state (login, or a tick)
//!
//! State lives in `~/.config/tezca/night.lua` — the same `return { … }` data
//! shape as every other generated file here. hyprsunset itself is stateless
//! across restarts, so something has to remember the temperature; `apply` is
//! what autostart.lua and the bar's minute tick both call.
//!
//! ## Scheduling
//!
//! hyprsunset has no scheduler of its own. Rather than generate systemd timers
//! (machine state in a third place, and a unit to clean up), the schedule is a
//! window stored here and evaluated by whoever calls `apply` — autostart at
//! login, and the bar once a minute when a schedule is set. `apply` is
//! idempotent, so calling it repeatedly costs one process and changes nothing.
//!
//! A window that wraps midnight (22:00 → 06:00) is the normal case, so the
//! comparison is written to handle it rather than assuming from < to.

use crate::{atomic, repo, term, util};
use std::path::PathBuf;
use std::process::{Command, Stdio};

const DEFAULT_NIGHT_TEMP: u32 = 4000;

#[derive(Clone, Debug, PartialEq)]
pub struct Night {
    /// Whether the filter is wanted at all.
    pub enabled: bool,
    /// Colour temperature in kelvin when active.
    pub temp: u32,
    /// Optional schedule, minutes from midnight.
    pub from: Option<u32>,
    pub to: Option<u32>,
}

impl Default for Night {
    fn default() -> Self {
        Night { enabled: false, temp: DEFAULT_NIGHT_TEMP, from: None, to: None }
    }
}

impl Night {
    /// Whether the filter should be *on right now*, given the wall clock in
    /// minutes from midnight.
    ///
    /// With no schedule, `enabled` alone decides. With one, the window gates it —
    /// and a window that wraps past midnight (22:00 → 06:00) is the common case,
    /// not an edge case.
    pub fn active_at(&self, now_min: u32) -> bool {
        if !self.enabled {
            return false;
        }
        match (self.from, self.to) {
            (Some(from), Some(to)) if from != to => {
                if from < to {
                    now_min >= from && now_min < to
                } else {
                    now_min >= from || now_min < to
                }
            }
            _ => true,
        }
    }
}

pub fn run(args: &[&str]) -> i32 {
    let r = match args.first().copied() {
        None | Some("status") => cmd_status(args.get(1..).unwrap_or(&[])),
        Some("on") => cmd_switch(Some(true)),
        Some("off") => cmd_switch(Some(false)),
        Some("toggle") => cmd_switch(None),
        Some("temp") => cmd_temp(&args[1..]),
        Some("schedule") => cmd_schedule(&args[1..]),
        Some("apply") => cmd_apply(),
        Some("-h") | Some("--help") => {
            print_help();
            Ok(())
        }
        Some(other) => Err(format!(
            "unknown night subcommand: {other}\n  try: status · on · off · toggle · \
             temp <K> · schedule <HH:MM> <HH:MM> · apply"
        )),
    };
    match r {
        Ok(()) => 0,
        Err(e) => {
            eprintln!("{} {e}", term::red("error:"));
            1
        }
    }
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

const HEADER: &str = "\
-- ~/.config/tezca/night.lua — generated by `tezca night`.
--
-- Night-light (blue-light filter) state. hyprsunset does not remember anything
-- across restarts, so this is what `tezca night apply` re-asserts at login and
-- on the bar's minute tick.
--
-- `from`/`to` are minutes from midnight; a window may wrap past midnight.
";

fn path() -> Result<PathBuf, String> {
    Ok(repo::config_home()?.join("tezca").join("night.lua"))
}

pub fn read() -> Night {
    let text = path().ok().and_then(|p| std::fs::read_to_string(p).ok()).unwrap_or_default();
    parse(&text)
}

fn parse(text: &str) -> Night {
    let mut n = Night::default();
    for line in text.lines() {
        let line = line.trim().trim_end_matches(',');
        let Some((k, v)) = line.split_once('=') else { continue };
        let (k, v) = (k.trim(), v.trim());
        match k {
            "enabled" => n.enabled = v == "true",
            "temp" => n.temp = v.parse().unwrap_or(DEFAULT_NIGHT_TEMP),
            "from" => n.from = v.parse().ok(),
            "to" => n.to = v.parse().ok(),
            _ => {}
        }
    }
    n
}

fn render(n: &Night) -> String {
    let mut s = String::from(HEADER);
    s.push_str("\nreturn {\n");
    s.push_str(&format!("    enabled = {},\n", n.enabled));
    s.push_str(&format!("    temp = {},\n", n.temp));
    match (n.from, n.to) {
        (Some(f), Some(t)) => {
            s.push_str(&format!("    from = {f},\n"));
            s.push_str(&format!("    to = {t},\n"));
        }
        _ => s.push_str("    -- no schedule: `enabled` alone decides\n"),
    }
    s.push_str("}\n");
    s
}

fn write(n: &Night) -> Result<(), String> {
    atomic::write(&path()?, &render(n))
}

// ---------------------------------------------------------------------------
// hyprsunset
// ---------------------------------------------------------------------------

/// Did a `hyprctl hyprsunset …` call actually do anything?
///
/// It answers `ok` on success — and, when no daemon is listening, prints
/// `Couldn't connect to …/.hyprsunset.sock. (3)` **and still exits 0**. So
/// success cannot be judged on the exit status, and it cannot be judged by
/// looking for words like "error" or "invalid" either: that message contains
/// none of them. The only reliable test is the positive one. (Observed on
/// hyprsunset 0.4.0 / Hyprland 0.56.1; the same exit-0-refusal shape `hypr.rs`
/// already documents for `hyprctl keyword`.)
fn ctl_succeeded(stdout: &str) -> bool {
    stdout.trim().eq_ignore_ascii_case("ok")
}

/// Send one command to a running hyprsunset daemon. False when none is listening.
fn hyprsunset_ctl(args: &[&str]) -> bool {
    let mut argv = vec!["hyprsunset"];
    argv.extend_from_slice(args);
    Command::new("hyprctl")
        .args(&argv)
        .output()
        .ok()
        .map(|o| ctl_succeeded(&String::from_utf8_lossy(&o.stdout)))
        .unwrap_or(false)
}

/// Apply a screen temperature now — `None` restores the unfiltered display.
///
/// Prefers the running daemon (no new process, and it applies instantly), and
/// starts one when there is nothing listening. `identity` is hyprsunset's own
/// term for "no adjustment", which is a truer "off" than asking for 6500 K.
fn set_temperature(kelvin: Option<u32>) -> Result<(), String> {
    if !util::has("hyprsunset") {
        return Err("hyprsunset not found — install it (`paru -S hyprsunset`)".into());
    }
    let temp = kelvin.map(|k| k.to_string());
    let ctl_args: Vec<&str> = match &temp {
        Some(t) => vec!["temperature", t.as_str()],
        None => vec!["identity"],
    };
    if hyprsunset_ctl(&ctl_args) {
        return Ok(());
    }

    // Nothing is listening and nothing is wanted: there is no filter to remove,
    // so starting a daemon purely to tell it "do nothing" would leave a resident
    // process at every login for no reason.
    if kelvin.is_none() {
        return Ok(());
    }

    // Nothing listening: start a daemon in the wanted state. Detached, with its
    // stdio nulled — it outlives us, and a caller capturing our output would
    // otherwise block waiting for a pipe the daemon never closes.
    let mut cmd = if util::has("setsid") {
        let mut c = Command::new("setsid");
        c.arg("hyprsunset");
        c
    } else {
        Command::new("hyprsunset")
    };
    if let Some(t) = &temp {
        cmd.args(["-t", t]);
    } else {
        cmd.arg("--identity");
    }
    cmd.stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|e| format!("failed to start hyprsunset: {e}"))?;
    Ok(())
}

/// Minutes from midnight, from the system clock.
fn now_minutes() -> u32 {
    // `date +%H:%M` rather than a time crate: this binary has no dependencies,
    // and the alternative is hand-rolling a timezone-correct local time out of
    // SystemTime, which is exactly the kind of code that is wrong twice a year.
    let out = Command::new("date").args(["+%H:%M"]).output().ok();
    let s = out
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default();
    parse_hhmm(&s).unwrap_or(0)
}

/// `HH:MM` → minutes from midnight.
fn parse_hhmm(s: &str) -> Option<u32> {
    let (h, m) = s.trim().split_once(':')?;
    let h: u32 = h.parse().ok()?;
    let m: u32 = m.parse().ok()?;
    (h < 24 && m < 60).then_some(h * 60 + m)
}

fn fmt_hhmm(min: u32) -> String {
    format!("{:02}:{:02}", min / 60, min % 60)
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

fn cmd_status(args: &[&str]) -> Result<(), String> {
    let n = read();
    let active = n.active_at(now_minutes());
    if args.iter().any(|a| *a == "--machine" || *a == "-m") {
        println!("enabled={}", n.enabled);
        println!("temp={}", n.temp);
        println!("from={}", n.from.map(fmt_hhmm).unwrap_or_default());
        println!("to={}", n.to.map(fmt_hhmm).unwrap_or_default());
        println!("active={active}");
        println!("available={}", util::has("hyprsunset"));
        return Ok(());
    }
    println!("{}", term::header("tezca night"));
    println!();
    if !util::has("hyprsunset") {
        println!("  {} {}", term::yellow("!"), term::dim("hyprsunset is not installed"));
    }
    println!(
        "  {} {:<10} {}",
        if active { term::green("●") } else { term::dim("○") },
        "night light",
        term::dim(&format!("{} K", n.temp))
    );
    match (n.from, n.to) {
        (Some(f), Some(t)) => println!(
            "  {} {:<10} {}",
            term::dim("·"),
            "schedule",
            term::dim(&format!("{} → {}", fmt_hhmm(f), fmt_hhmm(t)))
        ),
        _ => println!("  {} {:<10} {}", term::dim("·"), "schedule", term::dim("none")),
    }
    println!();
    Ok(())
}

fn cmd_switch(want: Option<bool>) -> Result<(), String> {
    let mut n = read();
    n.enabled = want.unwrap_or(!n.enabled);
    write(&n)?;
    apply(&n)?;
    println!("  {} night light {}", term::green("✓"), if n.enabled { "on" } else { "off" });
    Ok(())
}

fn cmd_temp(args: &[&str]) -> Result<(), String> {
    let v = args.first().copied().ok_or("usage: tezca night temp <1000-6500>")?;
    let kelvin: u32 =
        v.parse().map_err(|_| format!("invalid temperature {v:?} — expected kelvin, e.g. 4000"))?;
    if !(1000..=6500).contains(&kelvin) {
        return Err(format!("temperature {kelvin} is out of range — expected 1000-6500 K"));
    }
    let mut n = read();
    n.temp = kelvin;
    // Setting a temperature is asking for it: switching on too saves a step, and
    // "I set 4000 K and nothing happened" is a worse default.
    n.enabled = true;
    write(&n)?;
    apply(&n)?;
    println!("  {} night light at {kelvin} K", term::green("✓"));
    Ok(())
}

fn cmd_schedule(args: &[&str]) -> Result<(), String> {
    let mut n = read();
    match args.first().copied() {
        Some("off") | Some("none") | None => {
            n.from = None;
            n.to = None;
            write(&n)?;
            apply(&n)?;
            println!("  {} schedule cleared", term::green("✓"));
            Ok(())
        }
        Some(from) => {
            let to = args.get(1).copied().ok_or("usage: tezca night schedule <HH:MM> <HH:MM>")?;
            let f = parse_hhmm(from)
                .ok_or_else(|| format!("invalid time {from:?} — expected HH:MM"))?;
            let t =
                parse_hhmm(to).ok_or_else(|| format!("invalid time {to:?} — expected HH:MM"))?;
            if f == t {
                return Err("the start and end times are the same — that is not a window".into());
            }
            n.from = Some(f);
            n.to = Some(t);
            n.enabled = true;
            write(&n)?;
            apply(&n)?;
            println!("  {} night light {} → {}", term::green("✓"), fmt_hhmm(f), fmt_hhmm(t));
            Ok(())
        }
    }
}

fn cmd_apply() -> Result<(), String> {
    let n = read();
    // Nothing configured and nothing installed is the fresh-install state — say
    // nothing and exit cleanly, because autostart.lua calls this every login.
    if !n.enabled && !util::has("hyprsunset") {
        return Ok(());
    }
    apply(&n)
}

fn apply(n: &Night) -> Result<(), String> {
    if n.active_at(now_minutes()) {
        set_temperature(Some(n.temp))
    } else {
        set_temperature(None)
    }
}

fn print_help() {
    println!("{}", term::header("tezca night"));
    println!();
    for (c, d) in [
        ("status", "current state + schedule"),
        ("on | off | toggle", "the blue-light filter"),
        ("temp <K>", "colour temperature, 1000-6500 (switches it on)"),
        ("schedule <from> <to>", "e.g. 21:30 06:30 — may wrap past midnight"),
        ("schedule off", "clear the schedule"),
        ("apply", "re-assert the saved state (login / minute tick)"),
    ] {
        println!("  {:<22} {}", term::cyan(c), term::dim(d));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_schedule_that_wraps_past_midnight_is_the_normal_case() {
        let n = Night { enabled: true, temp: 4000, from: Some(22 * 60), to: Some(6 * 60) };
        assert!(n.active_at(23 * 60), "23:00 is inside 22:00→06:00");
        assert!(n.active_at(2 * 60), "02:00 is inside 22:00→06:00");
        assert!(n.active_at(22 * 60), "the window includes its start");
        assert!(!n.active_at(6 * 60), "the window excludes its end");
        assert!(!n.active_at(12 * 60), "midday is outside");
    }

    #[test]
    fn a_same_day_window_works_too() {
        let n = Night { enabled: true, temp: 4000, from: Some(9 * 60), to: Some(17 * 60) };
        assert!(n.active_at(12 * 60));
        assert!(!n.active_at(8 * 60));
        assert!(!n.active_at(18 * 60));
    }

    #[test]
    fn without_a_schedule_the_switch_alone_decides() {
        let on = Night { enabled: true, ..Default::default() };
        assert!(on.active_at(0));
        assert!(on.active_at(13 * 60));
        let off = Night { enabled: false, from: Some(0), to: Some(1439), ..Default::default() };
        assert!(!off.active_at(12 * 60), "a schedule never overrides the off switch");
    }

    #[test]
    fn round_trips_through_the_store() {
        for n in
            [Night::default(), Night { enabled: true, temp: 3200, from: Some(1290), to: Some(390) }]
        {
            assert_eq!(parse(&render(&n)), n);
        }
    }

    #[test]
    fn only_a_literal_ok_counts_as_the_daemon_having_answered() {
        // Both of these come out of `hyprctl hyprsunset …` with exit status 0.
        assert!(ctl_succeeded("ok\n"));
        assert!(ctl_succeeded("OK"));
        assert!(!ctl_succeeded(
            "Couldn't connect to /run/user/1000/hypr/…/.hyprsunset.sock. (3)\n"
        ));
        assert!(!ctl_succeeded(""));
        // The reason this is an allowlist: the real refusal contains none of the
        // words a denylist would look for, so a denylist reports success and the
        // daemon never gets started.
        let refusal = "Couldn't connect to /run/user/1000/hypr/x/.hyprsunset.sock. (3)";
        for word in ["error", "invalid", "unknown", "not found", "fail"] {
            assert!(!refusal.to_lowercase().contains(word), "denylist word {word:?} would miss it");
        }
    }

    #[test]
    fn parses_and_formats_clock_times() {
        assert_eq!(parse_hhmm("21:30"), Some(1290));
        assert_eq!(parse_hhmm("00:00"), Some(0));
        assert_eq!(parse_hhmm("24:00"), None);
        assert_eq!(parse_hhmm("21:60"), None);
        assert_eq!(parse_hhmm("nope"), None);
        assert_eq!(fmt_hhmm(1290), "21:30");
        assert_eq!(fmt_hhmm(0), "00:00");
    }
}
