//! `tezca keybind` — read + rebind Hyprland keybindings.
//!
//! The tezca-settings "Keybinds" page drives this. `list --machine` emits every
//! documented bind with its 1-based line number in the shipped `keybinds.conf`;
//! `rebind` changes a bind's modifier+key and `set-action` changes what it does
//! (dispatcher + args, e.g. which app it launches).
//!
//! ## An override layer, not an in-place rewrite
//!
//! These used to rewrite the matching line of `conf.d/keybinds.conf`. But
//! `~/.config/hypr` is a symlink into the repo, so every rebind edited a
//! **git-tracked file**: the working tree stayed dirty, a downstream clone could
//! not `git pull` without conflicting on the one file whose contents are pure
//! muscle memory, and the shipped map drifted invisibly from upstream.
//!
//! So the shipped map is now read-only, and changes go to a generated override
//! layer at `~/.config/tezca/keybinds.conf`, which `hyprland.conf` sources *after*
//! it. Each override releases the shipped combo with `unbind`, then binds the
//! replacement. That means the base map can't be corrupted, upstream changes to it
//! keep flowing, every local change is visible in one small file, and `reset` is
//! "delete the overrides" — an operation that cannot fail halfway.
//!
//! Every `unbind` is emitted *before* every `bind`. Interleaved, one entry's
//! `unbind` would cancel another entry's replacement whenever a combo is moved
//! from one bind to another.
//!
//! Three safety rails carry over, plus one new one:
//!   1. an `--expect` guard: the CLI refuses to touch a bind unless it still
//!      carries the combo the GUI showed (compared against the *effective* combo,
//!      overrides included);
//!   2. conflict detection: refuses (exit 2) if the target combo is already used
//!      by another bind, unless `--force`;
//!   3. a snapshot of the override layer before every write, so `restore` undoes
//!      the last change;
//!   4. input validation (`crate::validate`) — a combo containing a comma or a
//!      newline used to be written straight through, which could inject a whole
//!      extra directive. See that module for why `--expect` cannot catch it.
//!
//! Each override records the base combo it replaced (`was=`). If an upstream
//! change makes line N a *different* bind, the override is reported as stale and
//! skipped, rather than silently applied to the wrong key.

use crate::{atomic, hypr, repo, term, validate};
use std::fs;
use std::path::PathBuf;

/// Header for the generated override file. The whole file is generated, so this
/// points hand edits at `conf.d/local.conf` instead.
const OVERRIDE_HEADER: &str = "\
# ~/.config/tezca/keybinds.conf — generated by `tezca keybind`. Do not hand-edit.
#
# Sourced by hyprland.conf AFTER conf.d/keybinds.conf, so these win. Each entry
# releases the shipped combo with `unbind` and binds the replacement; the `was=`
# note records which shipped bind it replaced, so a later upstream change to
# keybinds.conf is reported as stale instead of silently rebinding the wrong key.
#
# `tezca keybind restore` undoes the last change; `tezca keybind reset` drops all
# of them and returns to the shipped map. For extra binds of your own that Tezca
# should never touch, use conf.d/local.conf.
";

/// The shipped bind map. Read-only — nothing in this module writes to it.
fn base_path() -> Result<PathBuf, String> {
    Ok(repo::config_home()?.join("hypr").join("conf.d").join("keybinds.conf"))
}

/// The generated override layer.
fn override_path() -> Result<PathBuf, String> {
    Ok(repo::config_home()?.join("tezca").join("keybinds.conf"))
}

/// Snapshot of the override layer taken before every write, for `restore`.
fn backup_path() -> Result<PathBuf, String> {
    let base = std::env::var_os("XDG_CACHE_HOME")
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty())
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".cache")))
        .ok_or("neither $XDG_CACHE_HOME nor $HOME is set")?;
    Ok(base.join("tezca").join("backups").join("keybind-overrides.prev"))
}

/// Create the override file if absent, so Hyprland's `source` never errors on a
/// fresh install. Returns whether it created anything. Called by `tezca link`.
pub fn seed() -> Result<bool, String> {
    let p = override_path()?;
    if p.exists() {
        return Ok(false);
    }
    atomic::write(&p, OVERRIDE_HEADER)?;
    Ok(true)
}

pub fn run(args: &[&str]) -> i32 {
    let r = match args.first().copied() {
        None | Some("list") => cmd_list(args.get(1..).unwrap_or(&[])),
        Some("rebind") => return cmd_rebind(&args[1..]),
        Some("set-action") => cmd_set_action(&args[1..]),
        Some("restore") => cmd_restore(),
        Some("reset") => cmd_reset(),
        Some("-h") | Some("--help") => {
            print_help();
            Ok(())
        }
        Some(other) => Err(format!(
            "unknown keybind subcommand: {other}\n  try: list · rebind --line N … · \
             set-action --line N … · restore · reset"
        )),
    };
    match r {
        Ok(()) => 0,
        Err(e) => {
            eprintln!("{} {e}", term::red("error:"));
            1
        }
    }
}

// ---------------------------------------------------------------------------
// Parsing the shipped map
// ---------------------------------------------------------------------------

/// A parsed bind (1-based `line` in the shipped map).
#[derive(Clone, Debug, PartialEq)]
struct Bind {
    line: usize,
    flags: String, // "bind", "binde", "bindl", "bindel", "bindm"
    mods: String,  // normalized, $mod → SUPER
    key: String,
    desc: String,   // trailing `# comment`, or "" if undocumented
    action: String, // dispatcher + args, e.g. "exec, uwsm app -- brave"
    /// True when an override-layer entry replaced this bind.
    overridden: bool,
}

/// Parse `bind[flags] = MODS, KEY, dispatcher…  # desc` — None if not a bind.
fn parse_bind(no: usize, raw: &str) -> Option<Bind> {
    let line = raw.trim();
    if !line.starts_with("bind") {
        return None;
    }
    let eq = line.find('=')?;
    let flags = line[..eq].trim().to_string();
    if !flags.chars().all(|c| c.is_ascii_lowercase()) {
        return None; // e.g. a "bindings" comment — not a real bind keyword
    }
    let body = &line[eq + 1..];
    let (before, desc) = match body.split_once('#') {
        Some((b, d)) => (b, d.trim().to_string()),
        None => (body, String::new()),
    };
    let mut it = before.splitn(3, ',');
    let mods = it.next().unwrap_or("").trim().replace("$mod", "SUPER");
    let key = it.next().unwrap_or("").trim().to_string();
    let action = it.next().unwrap_or("").trim().to_string();
    Some(Bind { line: no, flags, mods, key, desc, action, overridden: false })
}

/// "# ==== Title ====" / "# ---- Title ----" → the inner Title.
fn section_title(line: &str) -> Option<String> {
    let c = line.trim().strip_prefix('#')?.trim();
    let first = c.as_bytes().first().copied()?;
    if first != b'=' && first != b'-' {
        return None;
    }
    let inner = c.trim_matches(|ch| ch == '=' || ch == '-' || ch == ' ');
    (!inner.is_empty()).then(|| inner.to_string())
}

// ---------------------------------------------------------------------------
// The override layer
// ---------------------------------------------------------------------------

/// One entry of the override layer: what line N of the shipped map became.
#[derive(Clone, Debug, PartialEq)]
struct Ovr {
    line: usize,
    /// The shipped combo this entry replaced, recorded so a later upstream change
    /// to `keybinds.conf` is detected instead of silently misapplied.
    was_mods: String,
    was_key: String,
    flags: String,
    mods: String,
    key: String,
    action: String,
    desc: String,
}

/// `# @42 was=$mod|W` — the entry header. `|` separates the recorded combo, so a
/// comma in neither field can be ambiguous, and an empty modifier list is legal
/// (`was=|XF86AudioMute`) because plenty of media binds have no modifier.
fn parse_ovr_header(line: &str) -> Option<(usize, String, String)> {
    let rest = line.trim().strip_prefix("# @")?;
    let (num, was) = rest.split_once(" was=")?;
    let n: usize = num.trim().parse().ok()?;
    let (mods, key) = was.split_once('|')?;
    Some((n, mods.trim().to_string(), key.trim().to_string()))
}

/// Parse the override layer out of already-read text.
fn parse_overrides(text: &str) -> Vec<Ovr> {
    let mut out: Vec<Ovr> = Vec::new();
    let mut pending: Option<(usize, String, String)> = None;
    for raw in text.lines() {
        if let Some(h) = parse_ovr_header(raw) {
            pending = Some(h);
            continue;
        }
        let Some((line, was_mods, was_key)) = pending.clone() else { continue };
        // `parse_bind`'s line argument is only a label here; the header is the key.
        if let Some(b) = parse_bind(line, raw) {
            out.push(Ovr {
                line,
                was_mods,
                was_key,
                flags: b.flags,
                mods: b.mods,
                key: b.key,
                action: b.action,
                desc: b.desc,
            });
            pending = None;
        }
    }
    out
}

/// Read the override layer. A missing file simply means "no overrides".
fn load_overrides() -> Result<Vec<Ovr>, String> {
    let p = override_path()?;
    Ok(fs::read_to_string(&p).map(|t| parse_overrides(&t)).unwrap_or_default())
}

/// Serialize the override layer.
///
/// Every `unbind` is emitted before every `bind`: interleaved, moving a combo from
/// one bind to another would have the donor's `unbind` cancel the recipient's new
/// `bind` whenever the donor sorted later.
fn render_overrides(ovrs: &[Ovr]) -> String {
    let mut s = String::from(OVERRIDE_HEADER);
    if ovrs.is_empty() {
        return s;
    }
    let mut sorted = ovrs.to_vec();
    sorted.sort_by_key(|o| o.line);

    s.push_str("\n# --- release the shipped combos being replaced ---\n");
    for o in &sorted {
        s.push_str(&format!("unbind = {}, {}\n", house_mods(&o.was_mods), o.was_key));
    }
    s.push_str("\n# --- replacements ---\n");
    for o in &sorted {
        let comment = if o.desc.is_empty() { String::new() } else { format!("  # {}", o.desc) };
        s.push_str(&format!("# @{} was={}|{}\n", o.line, o.was_mods, o.was_key));
        s.push_str(&format!(
            "{} = {}, {}, {}{}\n",
            o.flags,
            house_mods(&o.mods),
            o.key,
            o.action,
            comment
        ));
    }
    s
}

/// Write the override layer, snapshotting the previous contents for `restore`.
fn save_overrides(ovrs: &[Ovr]) -> Result<(), String> {
    let p = override_path()?;
    let previous = fs::read_to_string(&p).unwrap_or_else(|_| OVERRIDE_HEADER.to_string());
    atomic::write(&backup_path()?, &previous)?;
    atomic::write(&p, &render_overrides(ovrs))
}

/// Apply the override layer to the shipped map.
///
/// An entry whose recorded `was=` combo no longer matches line N is **stale** —
/// the shipped map changed underneath it — so it is skipped and reported rather
/// than applied to whatever bind now occupies that line.
fn apply_overrides(base: &str, ovrs: &[Ovr]) -> (Vec<Bind>, Vec<Ovr>) {
    let mut binds = Vec::new();
    let mut stale = Vec::new();
    for (i, raw) in base.lines().enumerate() {
        let Some(mut b) = parse_bind(i + 1, raw) else { continue };
        if let Some(o) = ovrs.iter().find(|o| o.line == b.line) {
            if same_combo(&b.mods, &b.key, &o.was_mods, &o.was_key) {
                b.mods = o.mods.clone();
                b.key = o.key.clone();
                b.action = o.action.clone();
                b.desc = if o.desc.is_empty() { b.desc } else { o.desc.clone() };
                b.overridden = true;
            } else {
                stale.push(o.clone());
            }
        }
        binds.push(b);
    }
    (binds, stale)
}

/// The effective bind map: shipped, with overrides applied.
fn effective() -> Result<(Vec<Bind>, Vec<Ovr>), String> {
    let base =
        fs::read_to_string(base_path()?).map_err(|e| format!("cannot read keybinds.conf: {e}"))?;
    let ovrs = load_overrides()?;
    Ok(apply_overrides(&base, &ovrs))
}

fn warn_stale(stale: &[Ovr]) {
    for o in stale {
        eprintln!(
            "  {} the override for line {} no longer matches the shipped map \
             (it recorded {}) — ignoring it; re-apply it from Settings",
            term::yellow("!"),
            o.line,
            format_combo(&o.was_mods, &o.was_key)
        );
    }
}

// ---------------------------------------------------------------------------
// list
// ---------------------------------------------------------------------------

/// `tezca keybind list [--machine]` — documented binds with line numbers.
/// Machine format:  `S\t<title>`  for a section,
/// `B\t<line>\t<mods>\t<key>\t<desc>\t<action>\t<overridden 0|1>` for a bind.
/// The trailing field is appended, so a parser that reads five fields and ignores
/// the rest keeps working.
fn cmd_list(args: &[&str]) -> Result<(), String> {
    let base =
        fs::read_to_string(base_path()?).map_err(|e| format!("cannot read keybinds.conf: {e}"))?;
    let (binds, stale) = apply_overrides(&base, &load_overrides()?);
    let machine = args.iter().any(|a| *a == "--machine" || *a == "-m");
    if !machine {
        warn_stale(&stale);
    }

    for (i, raw) in base.lines().enumerate() {
        if let Some(title) = section_title(raw) {
            if machine {
                println!("S\t{title}");
            } else {
                println!("\n{}", term::bold(&title));
            }
            continue;
        }
        let Some(b) = binds.iter().find(|b| b.line == i + 1) else { continue };
        if b.desc.is_empty() {
            continue; // only surface documented binds
        }
        if machine {
            println!(
                "B\t{}\t{}\t{}\t{}\t{}\t{}",
                b.line,
                b.mods,
                b.key,
                b.desc,
                b.action,
                u8::from(b.overridden)
            );
        } else {
            let combo = format_combo(&b.mods, &b.key);
            let mark = if b.overridden { term::cyan("*") } else { " ".to_string() };
            println!("{mark} {:<24} {}", combo, term::dim(&b.desc));
        }
    }
    Ok(())
}

fn format_combo(mods: &str, key: &str) -> String {
    let mut parts: Vec<&str> = mods.split_whitespace().collect();
    if !key.is_empty() {
        parts.push(key);
    }
    parts.join(" + ")
}

// ---------------------------------------------------------------------------
// rebind
// ---------------------------------------------------------------------------

/// Returns a process exit code directly (2 = conflict, for the GUI to detect).
fn cmd_rebind(args: &[&str]) -> i32 {
    match rebind(args) {
        Ok(()) => 0,
        Err(RebindErr::Conflict(msg)) => {
            eprintln!("conflict: {msg}");
            2
        }
        Err(RebindErr::Other(e)) => {
            eprintln!("{} {e}", term::red("error:"));
            1
        }
    }
}

enum RebindErr {
    Conflict(String),
    Other(String),
}
impl From<String> for RebindErr {
    fn from(s: String) -> Self {
        RebindErr::Other(s)
    }
}

fn rebind(args: &[&str]) -> Result<(), RebindErr> {
    let mut line: Option<usize> = None;
    let mut mods = String::new();
    let mut key = String::new();
    let mut expect_mods: Option<String> = None;
    let mut expect_key: Option<String> = None;
    let mut force = false;

    let mut it = args.iter().copied();
    while let Some(a) = it.next() {
        match a {
            "--line" => line = it.next().and_then(|v| v.parse().ok()),
            "--mods" => mods = it.next().unwrap_or("").to_string(),
            "--key" => key = it.next().unwrap_or("").to_string(),
            "--expect-mods" => expect_mods = it.next().map(str::to_string),
            "--expect-key" => expect_key = it.next().map(str::to_string),
            "--force" => force = true,
            other => return Err(format!("unknown flag: {other}").into()),
        }
    }
    let line = line.ok_or_else(|| "rebind needs --line N".to_string())?;

    // Validate before anything is read or written: both values are formatted
    // verbatim into a config line.
    validate::keybind_mods(&mods)?;
    validate::keybind_key(&key)?;

    let (binds, stale) = effective()?;
    warn_stale(&stale);
    let target = binds
        .iter()
        .find(|b| b.line == line)
        .ok_or_else(|| format!("line {line} is not a bind line"))?
        .clone();
    reject_hold_bind(&target)?;

    // Guard: the bind must still carry the combo the GUI showed us — compared
    // against the *effective* combo, since that is what was displayed.
    if let (Some(em), Some(ek)) = (&expect_mods, &expect_key) {
        if !same_combo(&target.mods, &target.key, em, ek) {
            return Err("the keybindings changed since they were read — reopen Settings \
                        and try again"
                .to_string()
                .into());
        }
    }

    // Conflict check against every other bind, as it effectively stands.
    if !force {
        if let Some(other) = conflict(&binds, line, &mods, &key) {
            let what =
                if other.desc.is_empty() { format!("line {}", other.line) } else { other.desc };
            return Err(RebindErr::Conflict(format!(
                "{} is already bound to {what}",
                format_combo(&display_mods(&mods), &normalize_key(&key))
            )));
        }
    }

    // Read the shipped combo straight from the base map: that is what the override
    // has to release, and it stays correct across repeated rebinds.
    let base_bind = shipped(line)?;
    let ovr = Ovr {
        line,
        was_mods: base_bind.mods.clone(),
        was_key: base_bind.key.clone(),
        flags: base_bind.flags.clone(),
        mods: display_mods(&mods),
        key: normalize_key(&key),
        // Carry the effective action/desc, so a previous `set-action` is not lost.
        action: target.action.clone(),
        desc: target.desc.clone(),
    };
    commit(ovr, &base_bind)?;

    println!(
        "  {} {} → {}",
        term::green("✓"),
        term::dim(&format!("line {line}")),
        format_combo(&display_mods(&mods), &normalize_key(&key))
    );
    Ok(())
}

/// `bindm` is a hold-bind; Hyprland's `unbind` does not release one, so an
/// override would leave both the old and the new binding active.
fn reject_hold_bind(b: &Bind) -> Result<(), String> {
    if b.flags == "bindm" {
        return Err(format!(
            "line {} is a `bindm` hold-bind, which cannot be overridden \
             (Hyprland's `unbind` does not release mouse/hold binds) — \
             edit conf.d/keybinds.conf directly",
            b.line
        ));
    }
    Ok(())
}

/// The first *other* bind that already uses this combo.
fn conflict(binds: &[Bind], skip_line: usize, mods: &str, key: &str) -> Option<Bind> {
    binds
        .iter()
        .find(|b| {
            if b.line == skip_line {
                return false;
            }
            // Hold-binds live in their own namespace, so sharing a combo with one
            // is not a conflict — that is how `$mod+Z` doubles as hold-to-move.
            if b.flags == "bindm" {
                return false;
            }
            same_combo(&b.mods, &b.key, mods, key)
        })
        .cloned()
}

/// The bind exactly as shipped, ignoring the override layer.
fn shipped(line: usize) -> Result<Bind, String> {
    let base =
        fs::read_to_string(base_path()?).map_err(|e| format!("cannot read keybinds.conf: {e}"))?;
    base.lines()
        .enumerate()
        .find_map(|(i, raw)| (i + 1 == line).then(|| parse_bind(line, raw)).flatten())
        .ok_or_else(|| format!("line {line} is not a bind line"))
}

/// Upsert an override — or drop it, when it would only restate the shipped bind.
fn commit(ovr: Ovr, base_bind: &Bind) -> Result<(), String> {
    let mut ovrs = load_overrides()?;
    ovrs.retain(|o| o.line != ovr.line);
    if !restates_shipped(&ovr, base_bind) {
        ovrs.push(ovr);
    }
    save_overrides(&ovrs)?;
    if hypr::in_session() {
        let _ = hypr::reload();
    }
    Ok(())
}

/// True when an override would say exactly what the shipped map already says, so
/// returning a key to its default leaves a clean override layer behind.
fn restates_shipped(o: &Ovr, base: &Bind) -> bool {
    same_combo(&o.mods, &o.key, &base.mods, &base.key)
        && o.action == base.action
        && o.desc == base.desc
}

// ---------------------------------------------------------------------------
// set-action  (change what a bind does — dispatcher + args)
// ---------------------------------------------------------------------------

/// `tezca keybind set-action --line N --action "exec, uwsm app -- firefox.desktop"
/// [--desc "Firefox"] [--expect-mods … --expect-key …]` — change one bind's
/// dispatcher+args (and optionally its label), keeping its combo.
fn cmd_set_action(args: &[&str]) -> Result<(), String> {
    let mut line: Option<usize> = None;
    let mut action: Option<String> = None;
    let mut desc: Option<String> = None;
    let mut expect_mods: Option<String> = None;
    let mut expect_key: Option<String> = None;

    let mut it = args.iter().copied();
    while let Some(a) = it.next() {
        match a {
            "--line" => line = it.next().and_then(|v| v.parse().ok()),
            "--action" => action = it.next().map(str::to_string),
            "--desc" => desc = it.next().map(str::to_string),
            "--expect-mods" => expect_mods = it.next().map(str::to_string),
            "--expect-key" => expect_key = it.next().map(str::to_string),
            other => return Err(format!("unknown flag: {other}")),
        }
    }
    let line = line.ok_or("set-action needs --line N")?;
    let action = action.ok_or("set-action needs --action")?.trim().to_string();

    validate::keybind_action(&action)?;
    if let Some(d) = &desc {
        validate::keybind_desc(d)?;
    }

    let (binds, stale) = effective()?;
    warn_stale(&stale);
    let target = binds
        .iter()
        .find(|b| b.line == line)
        .ok_or_else(|| format!("line {line} is not a bind line"))?
        .clone();
    reject_hold_bind(&target)?;

    if let (Some(em), Some(ek)) = (&expect_mods, &expect_key) {
        if !same_combo(&target.mods, &target.key, em, ek) {
            return Err(
                "the keybindings changed since they were read — reopen Settings and try again"
                    .into(),
            );
        }
    }

    let base_bind = shipped(line)?;
    let ovr = Ovr {
        line,
        was_mods: base_bind.mods.clone(),
        was_key: base_bind.key.clone(),
        flags: base_bind.flags.clone(),
        // Keep the combo as it effectively stands, so a previous rebind survives.
        mods: target.mods.clone(),
        key: target.key.clone(),
        action: action.clone(),
        desc: desc.filter(|s| !s.is_empty()).unwrap_or_else(|| target.desc.clone()),
    };
    commit(ovr, &base_bind)?;

    println!("  {} {} → {}", term::green("✓"), term::dim(&format!("line {line}")), action);
    Ok(())
}

fn cmd_restore() -> Result<(), String> {
    let bak = backup_path()?;
    let text = fs::read_to_string(&bak)
        .map_err(|_| "no snapshot to restore (change a keybinding first)".to_string())?;
    atomic::write(&override_path()?, &text)?;
    if hypr::in_session() {
        let _ = hypr::reload();
    }
    println!("  {} undid the last keybinding change", term::green("✓"));
    Ok(())
}

fn cmd_reset() -> Result<(), String> {
    let n = load_overrides()?.len();
    save_overrides(&[])?;
    if hypr::in_session() {
        let _ = hypr::reload();
    }
    println!("  {} dropped {n} override(s) — back to the shipped keybindings", term::green("✓"));
    Ok(())
}

// ---------------------------------------------------------------------------
// Combo helpers
// ---------------------------------------------------------------------------

/// Canonical modifier set for *comparison*: $mod→SUPER, uppercased, sorted,
/// de-duplicated. Plain alphabetical order, so two spellings of the same combo
/// compare equal (`$mod SHIFT ALT` and `$mod ALT SHIFT` both appear in the
/// shipped map).
fn normalize_mods(mods: &str) -> String {
    let mut parts: Vec<String> =
        mods.replace("$mod", "SUPER").split_whitespace().map(|s| s.to_uppercase()).collect();
    parts.sort();
    parts.dedup();
    parts.join(" ")
}

/// Canonical modifier set for *display and storage*: the Tezca modifier first,
/// then the rest alphabetically.
///
/// Distinct from [`normalize_mods`] on purpose. Sorting plain-alphabetically is
/// what makes two spellings compare equal, but it also renders `SUPER SHIFT` as
/// `SHIFT $mod`, which reads backwards next to the shipped map's `$mod SHIFT`.
/// Keeping the two apart also makes the override layer round-trip byte-for-byte:
/// what we store is exactly what re-parsing the file gives back.
fn display_mods(mods: &str) -> String {
    let canonical = normalize_mods(mods);
    let mut parts: Vec<&str> = canonical.split_whitespace().collect();
    parts.sort_by_key(|m| (*m != "SUPER", *m));
    parts.join(" ")
}

/// Write `$mod` for SUPER, matching the shipped file's house style.
fn house_mods(mods: &str) -> String {
    display_mods(mods).replace("SUPER", "$mod")
}

/// Tidy a key for writing: single letter → uppercase, arrows → lowercase.
fn normalize_key(key: &str) -> String {
    let k = key.trim();
    if k.len() == 1 && k.chars().all(|c| c.is_ascii_alphabetic()) {
        return k.to_uppercase();
    }
    match k.to_lowercase().as_str() {
        "left" | "right" | "up" | "down" => k.to_lowercase(),
        _ => k.to_string(),
    }
}

/// Do two combos mean the same bind? (order-independent mods, case-fold key).
fn same_combo(mods_a: &str, key_a: &str, mods_b: &str, key_b: &str) -> bool {
    normalize_mods(mods_a) == normalize_mods(mods_b)
        && key_a.trim().eq_ignore_ascii_case(key_b.trim())
}

fn print_help() {
    println!("{}", term::header("tezca keybind"));
    println!("{}", term::dim("  changes go to ~/.config/tezca/keybinds.conf;"));
    println!("{}", term::dim("  the shipped conf.d/keybinds.conf is never modified"));
    println!();
    println!(
        "  {}                    list effective binds (* = overridden)",
        term::cyan("list [--machine]")
    );
    println!(
        "  {}  rebind a line's combo",
        term::cyan("rebind --line N --mods \"SUPER SHIFT\" --key W")
    );
    println!(
        "  {}  change what a bind does",
        term::cyan("set-action --line N --action \"exec, uwsm app -- app.desktop\"")
    );
    println!("  {}                         undo the last change", term::cyan("restore"));
    println!("  {}                           drop every override", term::cyan("reset"));
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A trimmed stand-in for the shipped map, carrying the flag variants that
    /// actually appear in it (bind / binde / bindl / bindm).
    const BASE: &str = "\
# ==== Windows ====
bind = CTRL, Q,        killactive                 # close focused window
bind = $mod, W,        exec, uwsm app -- brave    # Browser
binde = $mod, C,       exec, code                 # Editor
bindm = $mod, Z,       movewindow                 # hold to move
# ---- Media ----
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_SINK@ toggle  # Mute
bind = $mod, T,        exec, alacritty            # Terminal
bind = $mod, U,        exec, undocumented-no-desc
";

    fn base_binds() -> Vec<Bind> {
        apply_overrides(BASE, &[]).0
    }

    fn at(line: usize) -> Bind {
        base_binds().into_iter().find(|b| b.line == line).unwrap()
    }

    /// An override of `line`, keeping the shipped action/desc.
    fn ovr(line: usize, mods: &str, key: &str) -> Ovr {
        let b = at(line);
        Ovr {
            line,
            was_mods: b.mods.clone(),
            was_key: b.key.clone(),
            flags: b.flags,
            mods: mods.to_string(),
            key: key.to_string(),
            action: b.action,
            desc: b.desc,
        }
    }

    #[test]
    fn parses_every_flag_variant_in_the_shipped_map() {
        let flags: Vec<String> = base_binds().iter().map(|b| b.flags.clone()).collect();
        assert_eq!(flags, ["bind", "bind", "binde", "bindm", "bindl", "bind", "bind"]);

        // $mod normalizes to SUPER for comparison; the action survives whole.
        let brave = at(3);
        assert_eq!(brave.mods, "SUPER");
        assert_eq!(brave.key, "W");
        assert_eq!(brave.action, "exec, uwsm app -- brave");
        assert_eq!(brave.desc, "Browser");

        // A bind with no modifier parses with an empty mods field.
        let mute = at(7);
        assert_eq!(mute.mods, "");
        assert_eq!(mute.key, "XF86AudioMute");
        assert_eq!(mute.flags, "bindl");
    }

    #[test]
    fn finds_section_titles_in_both_styles() {
        assert_eq!(section_title("# ==== Windows ====").as_deref(), Some("Windows"));
        assert_eq!(section_title("# ---- Media ----").as_deref(), Some("Media"));
        assert_eq!(section_title("# a normal comment"), None);
        assert_eq!(section_title("bind = $mod, W, exec, x"), None);
    }

    #[test]
    fn an_override_replaces_the_combo_but_keeps_the_action() {
        let (binds, stale) = apply_overrides(BASE, &[ovr(3, "SUPER SHIFT", "W")]);
        assert!(stale.is_empty());
        let b = binds.iter().find(|b| b.line == 3).unwrap();
        assert_eq!(b.mods, "SUPER SHIFT");
        assert_eq!(b.action, "exec, uwsm app -- brave", "the action must survive a rebind");
        assert!(b.overridden);
        assert!(!binds.iter().filter(|b| b.line != 3).any(|b| b.overridden));
    }

    #[test]
    fn a_stale_override_is_reported_and_the_shipped_bind_stands() {
        // The shipped map changed under the override: line 3 is no longer $mod+W.
        let mut o = ovr(3, "SUPER SHIFT", "W");
        o.was_key = "Q".to_string();
        let (binds, stale) = apply_overrides(BASE, &[o]);
        assert_eq!(stale.len(), 1, "the mismatch must be surfaced");
        let b = binds.iter().find(|b| b.line == 3).unwrap();
        assert_eq!(b.key, "W");
        assert!(!b.overridden);
    }

    #[test]
    fn every_unbind_is_emitted_before_every_bind() {
        // Move $mod+T (line 8) onto $mod+W, and $mod+W (line 3) elsewhere. If the
        // unbind for line 8 came after line 3's replacement, it would cancel it and
        // the combo would end up bound to nothing.
        let out = render_overrides(&[ovr(8, "SUPER", "W"), ovr(3, "SUPER SHIFT", "B")]);
        let last_unbind = out.rfind("\nunbind = ").expect("unbinds present");
        let first_bind = out.find("\nbind").expect("binds present");
        assert!(last_unbind < first_bind, "all unbinds must precede all binds:\n{out}");
    }

    #[test]
    fn the_override_layer_round_trips_through_render_and_parse() {
        let a = ovr(3, "SUPER SHIFT", "B");
        // An empty modifier list has to survive the `was=|Key` encoding.
        let b = ovr(7, "", "XF86AudioMute");
        let parsed = parse_overrides(&render_overrides(&[a.clone(), b.clone()]));
        assert_eq!(parsed, vec![a, b]);
    }

    #[test]
    fn a_hold_bind_cannot_be_overridden() {
        let e = reject_hold_bind(&at(5)).unwrap_err();
        assert!(e.contains("bindm"), "{e}");
        assert!(reject_hold_bind(&at(3)).is_ok());
    }

    #[test]
    fn a_hold_bind_sharing_a_combo_is_not_a_conflict_but_a_real_bind_is() {
        let binds = base_binds();
        // bindm is its own namespace: rebinding onto $mod+Z is allowed.
        assert!(conflict(&binds, 3, "SUPER", "Z").is_none());
        // A plain bind that already owns the combo is a real conflict.
        let c = conflict(&binds, 3, "SUPER", "T").expect("SUPER+T is the terminal bind");
        assert_eq!(c.desc, "Terminal");
        // Rebinding a line onto its own current combo is not a conflict.
        assert!(conflict(&binds, 3, "SUPER", "W").is_none());
    }

    #[test]
    fn conflict_detection_sees_through_the_override_layer() {
        // Line 8 has been moved off $mod+T, so $mod+T is free for line 3 now…
        let (binds, _) = apply_overrides(BASE, &[ovr(8, "SUPER ALT", "T")]);
        assert!(conflict(&binds, 3, "SUPER", "T").is_none());
        // …and its new combo is the one that is taken.
        assert!(conflict(&binds, 3, "SUPER ALT", "T").is_some());
    }

    #[test]
    fn an_override_that_restates_the_shipped_bind_is_dropped() {
        let base = at(3);
        let restated = Ovr {
            line: 3,
            was_mods: base.mods.clone(),
            was_key: base.key.clone(),
            flags: base.flags.clone(),
            mods: display_mods("$mod"),
            key: normalize_key("w"),
            action: base.action.clone(),
            desc: base.desc.clone(),
        };
        assert!(restates_shipped(&restated, &base), "a rebind back to $mod+W is the default");

        let moved = ovr(3, "SUPER SHIFT", "W");
        assert!(!restates_shipped(&moved, &base));
    }

    #[test]
    fn combos_compare_independently_of_modifier_order_and_key_case() {
        assert!(same_combo("SUPER SHIFT", "W", "SHIFT SUPER", "w"));
        assert!(same_combo("$mod", "W", "SUPER", "W"));
        assert!(!same_combo("SUPER", "W", "SUPER SHIFT", "W"));
        assert!(!same_combo("SUPER", "W", "SUPER", "Q"));
    }

    #[test]
    fn writes_super_back_out_in_the_house_style() {
        assert_eq!(house_mods("SUPER SHIFT"), "$mod SHIFT");
        assert_eq!(house_mods("SHIFT SUPER"), "$mod SHIFT", "input order must not matter");
        assert_eq!(house_mods("$mod ALT CTRL"), "$mod ALT CTRL");
        assert_eq!(house_mods("$mod"), "$mod");
        assert_eq!(house_mods(""), "");
        // Comparison order stays plain-alphabetical so equal combos compare equal.
        assert_eq!(normalize_mods("SUPER SHIFT"), "SHIFT SUPER");
        assert_eq!(normalize_key("w"), "W");
        assert_eq!(normalize_key("Left"), "left");
        assert_eq!(normalize_key("XF86AudioMute"), "XF86AudioMute");
    }

    #[test]
    fn an_empty_override_layer_renders_to_just_the_header() {
        let out = render_overrides(&[]);
        assert_eq!(out, OVERRIDE_HEADER);
        // The header prose mentions `unbind`; what must be absent is a directive.
        assert!(!out.lines().any(|l| l.starts_with("unbind")));
        assert!(parse_overrides(&out).is_empty());
    }
}
