//! `tezca idle` — idle timeouts (lock / screen off / suspend) and "keep awake".
//!
//!   status [--machine]
//!   set [--lock N|off] [--dpms N|off] [--suspend N|off]
//!   apply                      regenerate the config and restart hypridle
//!   inhibit on|off|toggle      hold the session awake ("caffeine")
//!
//! ## Why this generates its own hypridle.conf
//!
//! `~/.config/hypr/hypridle.conf` is a symlink into the repo checkout, so the GUI
//! cannot write it without dirtying the working tree. hypridle takes `-c <path>`,
//! so instead we generate `~/.config/tezca/hypridle.conf` and autostart.lua
//! launches hypridle against it *when it exists*, falling back to the shipped
//! file otherwise. Machine-local state stays out of the repo, and deleting the
//! generated file restores the shipped behaviour exactly.
//!
//! The generated file is also its own store: each listener is preceded by a
//! `# tezca: <key> = <seconds>` marker, which is what [`read`] parses back. One
//! file, no second source of truth to drift.
//!
//! ## Inhibit
//!
//! "Keep awake" is a supervised `systemd-inhibit --what=idle` child whose PID is
//! tracked in `~/.cache/tezca/inhibit.pid`. This works because the shipped
//! hypridle config sets `ignore_systemd_inhibit = false` — hypridle honours the
//! inhibitor and stops counting. The PID is tracked rather than pattern-killed:
//! `pkill -f systemd-inhibit` would take out anybody else's inhibitor too.

use crate::{atomic, repo, term, util};
use std::path::PathBuf;
use std::process::{Command, Stdio};

/// A generated idle timeline. `None` = that listener is not installed at all.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Idle {
    /// Seconds until the session locks.
    pub lock: Option<u32>,
    /// Seconds until the displays power down.
    pub dpms: Option<u32>,
    /// Seconds until the machine suspends.
    pub suspend: Option<u32>,
}

pub fn run(args: &[&str]) -> i32 {
    let r = match args.first().copied() {
        None | Some("status") => cmd_status(args.get(1..).unwrap_or(&[])),
        Some("set") => cmd_set(&args[1..]),
        Some("apply") => cmd_apply(),
        Some("inhibit") => cmd_inhibit(&args[1..]),
        Some("-h") | Some("--help") => {
            print_help();
            Ok(())
        }
        Some(other) => Err(format!(
            "unknown idle subcommand: {other}\n  try: status · set --lock N · apply · inhibit on|off"
        )),
    };
    match r {
        Ok(()) => 0,
        Err(e) => {
            eprintln!("{} {e}", term::red("error:"));
            1
        }
    }
}

// ---------------------------------------------------------------------------
// The generated config
// ---------------------------------------------------------------------------

fn path() -> Result<PathBuf, String> {
    Ok(repo::config_home()?.join("tezca").join("hypridle.conf"))
}

const HEADER: &str = "\
# ~/.config/tezca/hypridle.conf — generated by `tezca idle`.
#
# hypridle is launched against this file by conf.d/autostart.lua whenever it
# exists. Delete it and you get the shipped ~/.config/hypr/hypridle.conf back.
#
# The `# tezca:` marker above each listener is how `tezca idle status` reads the
# timeline back, so keep it with its listener if you edit by hand.
";

/// Render the timeline. `lock_cmd` is always kept, so a manual lock
/// (SUPER+SHIFT+L, `loginctl lock-session`) still works even with every listener
/// switched off.
fn render(idle: &Idle) -> String {
    let mut s = String::from(HEADER);
    s.push_str(
        "\ngeneral {\n    \
         lock_cmd = pidof hyprlock || uwsm app -- hyprlock\n    \
         before_sleep_cmd = loginctl lock-session\n    \
         after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ state = \"on\" })'\n    \
         ignore_dbus_inhibit = false\n    \
         ignore_systemd_inhibit = false\n}\n",
    );

    if let Some(t) = idle.lock {
        s.push_str(&format!(
            "\n# tezca: lock = {t}\nlistener {{\n    timeout = {t}\n    \
             on-timeout = loginctl lock-session\n}}\n"
        ));
    }
    if let Some(t) = idle.dpms {
        s.push_str(&format!(
            "\n# tezca: dpms = {t}\nlistener {{\n    timeout = {t}\n    \
             on-timeout = hyprctl dispatch 'hl.dsp.dpms({{ state = \"off\" }})'\n    \
             on-resume = hyprctl dispatch 'hl.dsp.dpms({{ state = \"on\" }})'\n}}\n"
        ));
    }
    if let Some(t) = idle.suspend {
        s.push_str(&format!(
            "\n# tezca: suspend = {t}\nlistener {{\n    timeout = {t}\n    \
             on-timeout = systemctl suspend\n}}\n"
        ));
    }
    if idle.lock.is_none() && idle.dpms.is_none() && idle.suspend.is_none() {
        s.push_str("\n# No listeners: the session never idles on its own (\"always on\").\n");
    }
    s
}

fn parse(text: &str) -> Idle {
    let mut idle = Idle::default();
    for line in text.lines() {
        let Some(rest) = line.trim().strip_prefix("# tezca:") else { continue };
        let Some((k, v)) = rest.split_once('=') else { continue };
        let secs: Option<u32> = v.trim().parse().ok();
        match k.trim() {
            "lock" => idle.lock = secs,
            "dpms" => idle.dpms = secs,
            "suspend" => idle.suspend = secs,
            _ => {}
        }
    }
    idle
}

/// The configured timeline, or `None` when no generated config exists (in which
/// case the shipped always-on file is in force).
pub fn read() -> Result<Option<Idle>, String> {
    let p = path()?;
    match std::fs::read_to_string(&p) {
        Ok(text) => Ok(Some(parse(&text))),
        Err(_) => Ok(None),
    }
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

fn cmd_status(args: &[&str]) -> Result<(), String> {
    let generated = read()?;
    let idle = generated.clone().unwrap_or_default();
    let inhibited = inhibit_pid().is_some();

    if args.iter().any(|a| *a == "--machine" || *a == "-m") {
        println!("managed={}", generated.is_some());
        println!("lock={}", idle.lock.map(|v| v.to_string()).unwrap_or_default());
        println!("dpms={}", idle.dpms.map(|v| v.to_string()).unwrap_or_default());
        println!("suspend={}", idle.suspend.map(|v| v.to_string()).unwrap_or_default());
        println!("inhibited={inhibited}");
        println!("running={}", running());
        return Ok(());
    }

    println!("{}", term::header("tezca idle"));
    println!();
    if generated.is_none() {
        println!("  {}", term::dim("using the shipped config (no idle timers)"));
    }
    for (label, v) in
        [("lock", idle.lock), ("screen off", idle.dpms), ("suspend", idle.suspend)]
    {
        match v {
            Some(secs) => println!("  {} {:<12} {}", term::green("●"), label, term::dim(&fmt_secs(secs))),
            None => println!("  {} {:<12} {}", term::dim("○"), label, term::dim("never")),
        }
    }
    println!(
        "  {} {:<12} {}",
        if inhibited { term::green("●") } else { term::dim("○") },
        "keep awake",
        term::dim(if inhibited { "on" } else { "off" })
    );
    println!("  {} {:<12} {}", term::dim("·"), "hypridle", term::dim(if running() { "running" } else { "not running" }));
    println!();
    Ok(())
}

fn fmt_secs(s: u32) -> String {
    match s {
        0 => "immediately".to_string(),
        s if s % 3600 == 0 => format!("{} h", s / 3600),
        s if s % 60 == 0 => format!("{} min", s / 60),
        s => format!("{s} s"),
    }
}

fn cmd_set(args: &[&str]) -> Result<(), String> {
    let mut idle = read()?.unwrap_or_default();
    let mut it = args.iter().copied();
    let mut touched = false;
    while let Some(a) = it.next() {
        let field = match a {
            "--lock" => &mut idle.lock,
            "--dpms" | "--screen" => &mut idle.dpms,
            "--suspend" => &mut idle.suspend,
            other => return Err(format!("unknown flag: {other}")),
        };
        let v = it.next().ok_or_else(|| format!("{a} needs a value (seconds, or 'off')"))?;
        *field = match v {
            "off" | "never" | "0" => None,
            n => Some(n.parse::<u32>().map_err(|_| {
                format!("invalid value {n:?} for {a} — expected whole seconds, or 'off'")
            })?),
        };
        touched = true;
    }
    if !touched {
        return Err("usage: tezca idle set [--lock N|off] [--dpms N|off] [--suspend N|off]".into());
    }
    // A suspend that fires before the lock would leave an unlocked session on
    // resume. Ordering is checked rather than silently accepted.
    if let (Some(lock), Some(susp)) = (idle.lock, idle.suspend) {
        if susp < lock {
            return Err(format!(
                "suspend ({susp}s) would fire before the lock ({lock}s), which resumes to an \
                 unlocked session — set the lock timeout lower than suspend"
            ));
        }
    }
    atomic::write(&path()?, &render(&idle))?;
    apply_running()?;
    println!("  {} idle timeline updated", term::green("✓"));
    Ok(())
}

fn cmd_apply() -> Result<(), String> {
    // No generated config = nothing to apply; the shipped one is already in use.
    if read()?.is_none() {
        println!("  {} no generated config — using the shipped one", term::dim("·"));
        return Ok(());
    }
    apply_running()?;
    println!("  {} hypridle restarted with the generated config", term::green("✓"));
    Ok(())
}

fn running() -> bool {
    Command::new("pkill")
        .args(["-0", "-x", "hypridle"])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

/// Restart hypridle so a changed timeline takes effect now rather than at the
/// next login.
fn apply_running() -> Result<(), String> {
    if !util::has("hypridle") {
        return Ok(());
    }
    if running() {
        let _ = Command::new("pkill").args(["-TERM", "-x", "hypridle"]).status();
        for _ in 0..50 {
            if !running() {
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(20));
        }
    }
    let cfg = path()?;
    let mut cmd = if util::has("setsid") {
        let mut c = Command::new("setsid");
        c.arg("hypridle");
        c
    } else {
        Command::new("hypridle")
    };
    cmd.arg("-c")
        .arg(&cfg)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|e| format!("failed to start hypridle: {e}"))?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Inhibit ("keep awake")
// ---------------------------------------------------------------------------

fn pid_path() -> Result<PathBuf, String> {
    Ok(repo::cache_home()?.join("tezca").join("inhibit.pid"))
}

/// The live inhibitor's PID, if one is ours and still running.
fn inhibit_pid() -> Option<u32> {
    let p = pid_path().ok()?;
    let pid: u32 = std::fs::read_to_string(&p).ok()?.trim().parse().ok()?;
    // A stale pidfile outlives a reboot; check the process is really there
    // before reporting the session as held awake.
    std::path::Path::new(&format!("/proc/{pid}")).exists().then_some(pid)
}

fn cmd_inhibit(args: &[&str]) -> Result<(), String> {
    let current = inhibit_pid();
    let want = match args.first().copied() {
        Some("on") => true,
        Some("off") => false,
        Some("toggle") | None => current.is_none(),
        Some("status") => {
            println!("{}", if current.is_some() { "on" } else { "off" });
            return Ok(());
        }
        Some(other) => return Err(format!("expected on, off, toggle or status — got {other:?}")),
    };

    if want {
        if current.is_some() {
            println!("  {} already keeping the session awake", term::dim("·"));
            return Ok(());
        }
        if !util::has("systemd-inhibit") {
            return Err("systemd-inhibit not found".into());
        }
        let child = Command::new("systemd-inhibit")
            .args([
                "--what=idle",
                "--who=Tezca",
                "--why=Keep awake requested from Tezca",
                "--mode=block",
                "sleep",
                "infinity",
            ])
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .map_err(|e| format!("failed to start the inhibitor: {e}"))?;
        atomic::write(&pid_path()?, &format!("{}\n", child.id()))?;
        println!("  {} keeping the session awake", term::green("✓"));
    } else {
        match current {
            Some(pid) => {
                // Kill by the tracked PID, never by pattern: `pkill -f
                // systemd-inhibit` would also drop somebody else's inhibitor
                // (an in-progress update, a running backup).
                let _ = Command::new("kill").arg(pid.to_string()).status();
                let _ = std::fs::remove_file(pid_path()?);
                println!("  {} idle timers resumed", term::green("✓"));
            }
            None => println!("  {} not currently inhibited", term::dim("·")),
        }
    }
    Ok(())
}

fn print_help() {
    println!("{}", term::header("tezca idle"));
    println!();
    for (c, d) in [
        ("status", "the current timeline + inhibit state"),
        ("set --lock N", "seconds until the session locks ('off' to disable)"),
        ("set --dpms N", "seconds until the displays power down"),
        ("set --suspend N", "seconds until the machine suspends"),
        ("apply", "restart hypridle against the generated config"),
        ("inhibit on|off", "hold the session awake (\"caffeine\")"),
    ] {
        println!("  {:<20} {}", term::cyan(c), term::dim(d));
    }
    println!();
    println!("{}", term::dim("  Writes ~/.config/tezca/hypridle.conf; delete it to restore the shipped config."));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_a_timeline_through_the_generated_config() {
        let idle = Idle { lock: Some(600), dpms: Some(900), suspend: Some(1800) };
        let text = render(&idle);
        assert_eq!(parse(&text), idle);
        // The manual lock command survives even a fully disabled timeline, or
        // SUPER+SHIFT+L would stop working the moment you turned auto-lock off.
        let none = render(&Idle::default());
        assert!(none.contains("lock_cmd"));
        assert_eq!(parse(&none), Idle::default());
    }

    #[test]
    fn each_listener_is_emitted_only_when_set() {
        let only_lock = render(&Idle { lock: Some(300), ..Default::default() });
        assert!(only_lock.contains("# tezca: lock = 300"));
        assert!(!only_lock.contains("systemctl suspend"));
        // Not `contains("dpms")`: the general block legitimately mentions dpms in
        // `after_sleep_cmd`, which is how the screen comes back after a suspend.
        assert!(!only_lock.contains("# tezca: dpms"));
        assert_eq!(only_lock.matches("listener {").count(), 1);
        assert_eq!(parse(&only_lock).lock, Some(300));
        assert_eq!(parse(&only_lock).suspend, None);
    }

    #[test]
    fn dpms_dispatchers_use_lua_syntax_not_the_legacy_form() {
        // Under the Lua config manager `hyprctl dispatch dpms off` is rejected
        // outright — the argument string is parsed as Lua. A listener carrying
        // the legacy spelling would silently fail at the moment the screen was
        // supposed to blank.
        let text = render(&Idle { dpms: Some(900), ..Default::default() });
        assert!(text.contains(r#"hl.dsp.dpms({ state = "off" })"#));
        assert!(text.contains(r#"hl.dsp.dpms({ state = "on" })"#));
        assert!(!text.contains("dispatch dpms off"));
    }

    #[test]
    fn humanises_timeouts() {
        assert_eq!(fmt_secs(600), "10 min");
        assert_eq!(fmt_secs(3600), "1 h");
        assert_eq!(fmt_secs(90), "90 s");
    }
}
