//! `tezca startup` — what launches when you log in.
//!
//!   list [--machine]                     shipped services + your own entries
//!   add <command> [--label L] [--delay N] [--id ID]
//!   remove <id>
//!   enable <id> | disable <id>           works for shipped services too
//!   run <id>                             launch it now, to test it
//!
//! ## Why a data file and not "just edit autostart.lua"
//!
//! `conf.d/autostart.lua` is a symlink into the repo checkout. Adding an app by
//! editing it dirties the working tree, publishes machine-local choices, and
//! breaks `git pull` in a downstream clone. So the shipped list stays in the
//! repo, and *your* list lives in `~/.config/tezca/startup.lua`, which
//! autostart.lua reads through `util.load`.
//!
//! Like every other generated file here it is **data, not code**: a bare
//! `return { … }` table that the config only ever indexes into. A Lua error in
//! the Hyprland config is not a warning — it drops the session into emergency
//! mode, one keybind on a black screen — and `util.load` degrades a broken file
//! to `nil` rather than letting that happen.

use crate::{atomic, repo, term, validate};
use std::path::PathBuf;
use std::process::{Command, Stdio};

/// The services `conf.d/autostart.lua` launches, in the order it launches them.
///
/// Kept in step with that file by hand — it is a short, rarely-changing list, and
/// the alternative (parsing Lua to discover them) is far worse. `essential`
/// entries cannot be disabled from here: without the bar there is no way back to
/// the Settings window that would re-enable it.
const SHIPPED: &[(&str, &str, bool, &str)] = &[
    // (id, label, essential, what turning it off costs you)
    ("polkit", "Polkit agent", false, "GUI password prompts (mounting, pkexec) stop appearing"),
    ("cliphist-text", "Clipboard history (text)", false, "SUPER+V has no text history"),
    ("cliphist-image", "Clipboard history (images)", false, "SUPER+V has no image history"),
    ("tezca-bar", "Tezca menubar", true, ""),
    ("swaync", "Notification centre", false, "no notifications at all"),
    ("elephant", "Launcher backend", false, "SUPER+SPACE opens but finds nothing"),
    ("walker", "Launcher service", false, "SUPER+SPACE cold-starts (~1.2s instead of ~90ms)"),
    ("awww", "Wallpaper daemon", false, "no wallpaper — a flat obsidian background"),
    ("hypridle", "Idle daemon", false, "no idle lock or screen blanking"),
    ("tezca-dock", "Tezca dock", false, "the magnifying dock does not appear"),
    ("wallpaper", "Apply wallpaper", false, "the wallpaper is not painted at login"),
];

pub fn run(args: &[&str]) -> i32 {
    let r = match args.first().copied() {
        None | Some("list") => cmd_list(args.get(1..).unwrap_or(&[])),
        Some("add") => cmd_add(&args[1..]),
        Some("remove") | Some("rm") => cmd_remove(&args[1..]),
        Some("enable") => cmd_set_enabled(&args[1..], true),
        Some("disable") => cmd_set_enabled(&args[1..], false),
        Some("run") => cmd_run(&args[1..]),
        Some("-h") | Some("--help") => {
            print_help();
            Ok(())
        }
        Some(other) => Err(format!(
            "unknown startup subcommand: {other}\n  try: list · add <command> · remove <id> · \
             enable <id> · disable <id> · run <id>"
        )),
    };
    match r {
        Ok(()) => 0,
        Err(e) => {
            eprintln!("{} {e}", term::red("error:"));
            1
        }
    }
}

// ---------------------------------------------------------------------------
// The store
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Default, PartialEq)]
pub struct Entry {
    pub id: String,
    pub exec: String,
    pub label: String,
    pub enabled: bool,
    /// Seconds to wait before launching. Useful for anything that wants the bar
    /// and tray up first.
    pub delay: u32,
}

#[derive(Clone, Debug, Default, PartialEq)]
struct Store {
    entries: Vec<Entry>,
    /// Ids from [`SHIPPED`] the user has switched off.
    disabled: Vec<String>,
}

const HEADER: &str = "\
-- ~/.config/tezca/startup.lua — generated by `tezca startup`.
--
-- What launches at login, on top of (and alongside) the shipped services in
-- conf.d/autostart.lua. Read by that file through util.load, so a syntax error
-- here costs you these entries and nothing else — never the session.
--
-- DATA, not code: a bare `return { … }` table. `entries` are your own apps;
-- `disabled` lists shipped service ids you have turned off.
";

fn path() -> Result<PathBuf, String> {
    Ok(repo::config_home()?.join("tezca").join("startup.lua"))
}

/// Create the file if absent, so autostart.lua always finds something.
/// Called by `tezca link`.
pub fn seed() -> Result<bool, String> {
    let p = path()?;
    if p.exists() {
        return Ok(false);
    }
    atomic::write(&p, &render(&Store::default()))?;
    Ok(true)
}

fn read() -> Result<Store, String> {
    let text = std::fs::read_to_string(path()?).unwrap_or_default();
    Ok(parse(&text))
}

fn write(store: &Store) -> Result<(), String> {
    atomic::write(&path()?, &render(store))
}

/// Escape a value for a double-quoted Lua string.
fn lua_str(v: &str) -> String {
    format!("\"{}\"", v.replace('\\', "\\\\").replace('"', "\\\""))
}

fn unlua_str(lit: &str) -> String {
    let t = lit.trim().trim_end_matches(',').trim();
    match t.strip_prefix('"').and_then(|s| s.strip_suffix('"')) {
        Some(inner) => inner.replace("\\\"", "\"").replace("\\\\", "\\"),
        None => t.to_string(),
    }
}

fn render(store: &Store) -> String {
    let mut s = String::from(HEADER);
    s.push_str("\nreturn {\n    entries = {\n");
    for e in &store.entries {
        s.push_str(&format!(
            "        {{ id = {}, exec = {}, label = {}, enabled = {}, delay = {} }},\n",
            lua_str(&e.id),
            lua_str(&e.exec),
            lua_str(&e.label),
            e.enabled,
            e.delay
        ));
    }
    s.push_str("    },\n    disabled = {");
    if !store.disabled.is_empty() {
        s.push(' ');
        let ids: Vec<String> = store.disabled.iter().map(|d| lua_str(d)).collect();
        s.push_str(&ids.join(", "));
        s.push(' ');
    }
    s.push_str("},\n}\n");
    s
}

/// Line scanner over the grammar [`render`] emits — we are the only writer, so
/// the accepted grammar is exactly the produced one (same approach as the
/// override store).
fn parse(text: &str) -> Store {
    let mut store = Store::default();
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with("--") {
            continue;
        }
        if let Some(rest) = line.strip_prefix("disabled = {") {
            let inner = rest.trim_end_matches(',').trim().trim_end_matches('}');
            store.disabled = inner
                .split(',')
                .map(unlua_str)
                .filter(|s| !s.is_empty())
                .collect();
            continue;
        }
        if line.starts_with('{') && line.contains("exec") {
            if let Some(e) = parse_entry(line) {
                store.entries.push(e);
            }
        }
    }
    store
}

fn parse_entry(line: &str) -> Option<Entry> {
    let inner = line.trim().trim_start_matches('{').trim_end_matches(',').trim_end_matches('}');
    let mut e = Entry { enabled: true, ..Default::default() };
    // Split on commas that are not inside a quoted string — a label or command
    // may legitimately contain one ("Firefox, private window").
    for field in split_fields(inner) {
        let Some((k, v)) = field.split_once('=') else { continue };
        match k.trim() {
            "id" => e.id = unlua_str(v),
            "exec" => e.exec = unlua_str(v),
            "label" => e.label = unlua_str(v),
            "enabled" => e.enabled = v.trim().trim_end_matches(',').trim() != "false",
            "delay" => e.delay = unlua_str(v).parse().unwrap_or(0),
            _ => {}
        }
    }
    (!e.exec.is_empty()).then(|| {
        if e.id.is_empty() {
            e.id = slug(&e.exec);
        }
        if e.label.is_empty() {
            e.label = e.id.clone();
        }
        e
    })
}

/// Split `a = "x", b = 1` on top-level commas only.
fn split_fields(s: &str) -> Vec<String> {
    let mut out = vec![String::new()];
    let (mut in_str, mut escaped) = (false, false);
    for ch in s.chars() {
        if escaped {
            out.last_mut().expect("non-empty").push(ch);
            escaped = false;
            continue;
        }
        match ch {
            '\\' if in_str => {
                escaped = true;
                out.last_mut().expect("non-empty").push(ch);
            }
            '"' => {
                in_str = !in_str;
                out.last_mut().expect("non-empty").push(ch);
            }
            ',' if !in_str => out.push(String::new()),
            _ => out.last_mut().expect("non-empty").push(ch),
        }
    }
    out
}

/// A stable id derived from a command: `uwsm app -- discord.desktop` → `discord`.
///
/// The name is the *first* real word, not the last: `syncthing serve
/// --no-browser` is the syncthing entry, not the "serve" one. Launcher wrappers
/// and flags are skipped to get at it.
fn slug(exec: &str) -> String {
    const WRAPPERS: &[&str] = &["uwsm", "app", "--", "sh", "-c", "exec", "env", "systemd-run"];
    let word = exec
        .split_whitespace()
        .find(|w| !w.starts_with('-') && !WRAPPERS.contains(w))
        .unwrap_or("app");
    let base = word.rsplit('/').next().unwrap_or(word);
    let base = base.strip_suffix(".desktop").unwrap_or(base);
    let cleaned: String = base
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c } else { '-' })
        .collect();
    let cleaned = cleaned.trim_matches('-').to_lowercase();
    if cleaned.is_empty() { "app".to_string() } else { cleaned }
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

fn cmd_list(args: &[&str]) -> Result<(), String> {
    let store = read()?;
    let machine = args.iter().any(|a| *a == "--machine" || *a == "-m");

    if machine {
        for (id, label, essential, cost) in SHIPPED {
            println!("@service");
            println!("id={id}");
            println!("label={label}");
            println!("enabled={}", !store.disabled.iter().any(|d| d == id));
            println!("essential={essential}");
            println!("cost={cost}");
        }
        for e in &store.entries {
            println!("@entry");
            println!("id={}", e.id);
            println!("label={}", e.label);
            println!("exec={}", e.exec);
            println!("enabled={}", e.enabled);
            println!("delay={}", e.delay);
        }
        return Ok(());
    }

    println!("{}", term::header("tezca startup"));
    println!();
    println!("  {}", term::bold("Tezca services"));
    for (id, label, essential, _) in SHIPPED {
        let on = !store.disabled.iter().any(|d| d == id);
        let dot = if on { term::green("●") } else { term::dim("○") };
        let tag = if *essential { term::dim("  (essential)") } else { String::new() };
        println!("  {dot} {:<26} {}{tag}", term::bold(label), term::dim(id));
    }
    println!();
    println!("  {}", term::bold("Your apps"));
    if store.entries.is_empty() {
        println!("  {}", term::dim("none — `tezca startup add \"<command>\"`"));
    }
    for e in &store.entries {
        let dot = if e.enabled { term::green("●") } else { term::dim("○") };
        let delay = if e.delay > 0 { format!("  +{}s", e.delay) } else { String::new() };
        println!("  {dot} {:<26} {}", term::bold(&e.label), term::dim(&format!("{}{delay}", e.exec)));
    }
    println!();
    Ok(())
}

fn cmd_add(args: &[&str]) -> Result<(), String> {
    let mut exec = String::new();
    let mut label = String::new();
    let mut id = String::new();
    let mut delay: u32 = 0;

    let mut it = args.iter().copied();
    while let Some(a) = it.next() {
        match a {
            "--label" => label = it.next().ok_or("--label needs a value")?.to_string(),
            "--id" => id = it.next().ok_or("--id needs a value")?.to_string(),
            "--delay" => {
                delay = it
                    .next()
                    .and_then(|v| v.parse().ok())
                    .ok_or("--delay needs a whole number of seconds")?
            }
            // `--desktop foo.desktop` is what the GUI sends: uwsm resolves a
            // desktop id itself, so nothing here has to parse .desktop files.
            "--desktop" => {
                let app = it.next().ok_or("--desktop needs an application id")?;
                exec = format!("uwsm app -- {app}");
            }
            other if other.starts_with('-') => return Err(format!("unknown flag: {other}")),
            other => exec = other.to_string(),
        }
    }
    if exec.trim().is_empty() {
        return Err("usage: tezca startup add \"<command>\" [--label L] [--delay N]".into());
    }
    validate::exec_line(&exec)?;
    if !label.is_empty() {
        validate::exec_line(&label)?;
    }

    let mut store = read()?;
    let id = if id.is_empty() { slug(&exec) } else { id };
    validate::startup_id(&id)?;
    // Ids must be unique — they address an entry for enable/disable/remove.
    let id = unique_id(&store, &id);
    let label = if label.is_empty() { title_case(&id) } else { label };
    store.entries.push(Entry { id: id.clone(), exec, label: label.clone(), enabled: true, delay });
    write(&store)?;
    println!("  {} added {} ({id})", term::green("✓"), term::bold(&label));
    println!("  {}", term::dim("starts at your next login — `tezca startup run <id>` to test it now"));
    Ok(())
}

fn unique_id(store: &Store, base: &str) -> String {
    if !store.entries.iter().any(|e| e.id == base) {
        return base.to_string();
    }
    (2..).map(|n| format!("{base}-{n}")).find(|c| !store.entries.iter().any(|e| e.id == *c)).unwrap_or_default()
}

fn title_case(s: &str) -> String {
    let s = s.replace(['-', '_'], " ");
    let mut c = s.chars();
    match c.next() {
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        None => s.clone(),
    }
}

fn cmd_remove(args: &[&str]) -> Result<(), String> {
    let id = args.first().copied().ok_or("usage: tezca startup remove <id>")?;
    let mut store = read()?;
    let before = store.entries.len();
    store.entries.retain(|e| e.id != id);
    if store.entries.len() == before {
        return Err(format!("no startup entry with id '{id}' (see `tezca startup list`)"));
    }
    write(&store)?;
    println!("  {} removed {id}", term::green("✓"));
    Ok(())
}

fn cmd_set_enabled(args: &[&str], on: bool) -> Result<(), String> {
    let id = args
        .first()
        .copied()
        .ok_or_else(|| format!("usage: tezca startup {} <id>", if on { "enable" } else { "disable" }))?;
    let mut store = read()?;

    if let Some(e) = store.entries.iter_mut().find(|e| e.id == id) {
        e.enabled = on;
        let label = e.label.clone();
        write(&store)?;
        println!("  {} {label} {}", term::green("✓"), if on { "enabled" } else { "disabled" });
        return Ok(());
    }

    let Some((_, label, essential, cost)) = SHIPPED.iter().find(|(sid, _, _, _)| *sid == id) else {
        return Err(format!("no startup entry with id '{id}' (see `tezca startup list`)"));
    };
    if *essential && !on {
        return Err(format!(
            "'{id}' is essential and cannot be disabled — without it there is no way back \
             to the settings window that would switch it on again"
        ));
    }
    if on {
        store.disabled.retain(|d| d != id);
    } else if !store.disabled.iter().any(|d| d == id) {
        store.disabled.push(id.to_string());
    }
    write(&store)?;
    println!("  {} {label} {}", term::green("✓"), if on { "enabled" } else { "disabled" });
    if !on && !cost.is_empty() {
        println!("  {} {}", term::yellow("!"), term::dim(cost));
    }
    println!("  {}", term::dim("takes effect at your next login"));
    Ok(())
}

fn cmd_run(args: &[&str]) -> Result<(), String> {
    let id = args.first().copied().ok_or("usage: tezca startup run <id>")?;
    let store = read()?;
    let e = store
        .entries
        .iter()
        .find(|e| e.id == id)
        .ok_or_else(|| format!("no startup entry with id '{id}'"))?;
    // Through a shell, exactly as autostart.lua launches it, so testing an entry
    // exercises the same command line it will get at login.
    Command::new("sh")
        .arg("-c")
        .arg(&e.exec)
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|err| format!("could not launch: {err}"))?;
    println!("  {} launched {}", term::green("✓"), term::bold(&e.label));
    Ok(())
}

fn print_help() {
    println!("{}", term::header("tezca startup"));
    println!();
    for (c, d) in [
        ("list", "shipped services + your own entries"),
        ("add \"<cmd>\"", "add an app (--label, --delay N, --desktop id)"),
        ("remove <id>", "delete one of your entries"),
        ("enable <id>", "switch an entry or shipped service back on"),
        ("disable <id>", "switch one off (shipped services included)"),
        ("run <id>", "launch it now, without logging out"),
    ] {
        println!("  {:<18} {}", term::cyan(c), term::dim(d));
    }
    println!();
    println!("{}", term::dim("  Your list lives in ~/.config/tezca/startup.lua, outside the repo."));
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(id: &str, exec: &str) -> Entry {
        Entry {
            id: id.into(),
            exec: exec.into(),
            label: title_case(id),
            enabled: true,
            delay: 0,
        }
    }

    #[test]
    fn round_trips_entries_and_disabled_services() {
        let store = Store {
            entries: vec![
                entry("discord", "uwsm app -- discord.desktop"),
                Entry { delay: 5, enabled: false, ..entry("syncthing", "syncthing serve") },
            ],
            disabled: vec!["tezca-dock".into(), "hypridle".into()],
        };
        let text = render(&store);
        assert_eq!(parse(&text), store);
        // Rewriting is a fixed point — the file must not grow on repeated writes.
        assert_eq!(render(&parse(&text)), text);
    }

    #[test]
    fn a_command_containing_a_comma_or_a_quote_survives_the_round_trip() {
        // Both would have broken a naive `split(',')` / unquoted render — and the
        // failure mode is a *config file*, so it has to be right.
        let store = Store {
            entries: vec![entry("brave", r#"sh -c 'brave --args="a,b"'"#)],
            disabled: vec![],
        };
        let text = render(&store);
        assert_eq!(parse(&text), store);
        assert!(!text.contains("\n\n\n"));
    }

    #[test]
    fn an_empty_store_renders_a_table_that_is_still_valid_lua() {
        let text = render(&Store::default());
        assert!(text.contains("return {"));
        assert!(text.contains("entries = {"));
        assert!(text.contains("disabled = {},"));
        assert_eq!(parse(&text), Store::default());
    }

    #[test]
    fn derives_a_readable_id_from_a_command() {
        assert_eq!(slug("uwsm app -- discord.desktop"), "discord");
        assert_eq!(slug("syncthing serve --no-browser"), "syncthing");
        assert_eq!(slug("/usr/bin/nextcloud"), "nextcloud");
        assert_eq!(slug("uwsm app -- org.telegram.desktop.desktop"), "org-telegram-desktop");
        assert_eq!(slug(""), "app");
    }

    #[test]
    fn ids_stay_unique_so_enable_disable_addresses_one_entry() {
        let store = Store { entries: vec![entry("discord", "discord")], disabled: vec![] };
        assert_eq!(unique_id(&store, "discord"), "discord-2");
        assert_eq!(unique_id(&store, "slack"), "slack");
    }

    #[test]
    fn a_file_written_by_hand_without_optional_fields_still_loads() {
        let text = "return {\n  entries = {\n    { exec = \"foo --bar\" },\n  },\n}\n";
        let store = parse(text);
        assert_eq!(store.entries.len(), 1);
        assert_eq!(store.entries[0].exec, "foo --bar");
        assert_eq!(store.entries[0].id, "foo");
        assert!(store.entries[0].enabled, "an entry with no `enabled` key is on");
    }
}
