//! `tezca keybind` — read + rebind Hyprland keybindings.
//!
//! The tezca-settings "Keybinds" page drives this. `list --machine` emits every
//! documented bind with its 1-based line number in the shipped `keybinds.lua`;
//! `rebind` changes a bind's modifier+key and `set-action` changes what it does
//! (dispatcher + args, e.g. which app it launches).
//!
//! ## An override layer, not an in-place rewrite
//!
//! These used to rewrite the matching line of `conf.d/keybinds.lua`. But
//! `~/.config/hypr` is a symlink into the repo, so every rebind edited a
//! **git-tracked file**: the working tree stayed dirty, a downstream clone could
//! not `git pull` without conflicting on the one file whose contents are pure
//! muscle memory, and the shipped map drifted invisibly from upstream.
//!
//! So the shipped map is now read-only, and changes go to a generated override
//! layer at `~/.config/tezca/keybinds.lua`, which `hyprland.lua` loads *after*
//! it. Each override releases the shipped combo with `hl.unbind`, then binds the
//! replacement. That means the base map can't be corrupted, upstream changes to it
//! keep flowing, every local change is visible in one small file, and `reset` is
//! "delete the overrides" — an operation that cannot fail halfway.
//!
//! Every `hl.unbind` is emitted *before* every `hl.bind`. Interleaved, one
//! entry's unbind would cancel another entry's replacement whenever a combo is
//! moved from one bind to another. `hl.unbind` also matches the registered combo
//! string exactly and case-sensitively, so overrides always spell it out in full
//! (`"SUPER + Q"`) rather than reusing the shipped map's `mod` variable.
//!
//! Three safety rails carry over, plus one new one:
//!   1. an `--expect` guard: the CLI refuses to touch a bind unless it still
//!      carries the combo the GUI showed (compared against the *effective* combo,
//!      overrides included);
//!   2. conflict detection: refuses (exit 2) if the target combo is already used
//!      by another bind, unless `--force`;
//!   3. a snapshot of the override layer before every write, so `restore` undoes
//!      the last change;
//!   4. input validation (`crate::validate`) — a combo containing a comma or a
//!      newline used to be written straight through, which could inject a whole
//!      extra directive. See that module for why `--expect` cannot catch it.
//!
//! Each override records the base combo it replaced (`was=`). If an upstream
//! change makes line N a *different* bind, the override is reported as stale and
//! skipped, rather than silently applied to the wrong key.
//!
//! One bind in the shipped map — ALT+Tab — is a multi-line `function() … end`
//! body rather than a single dispatcher. It is listed (its combo is on one line)
//! but cannot be rebound, because this line-oriented reader cannot reproduce the
//! body into the override layer.

use crate::{atomic, hypr, repo, term, validate};
use std::fs;
use std::path::PathBuf;

/// Header for the generated override file. The whole file is generated, so this
/// points hand edits at `conf.d/local.lua` instead.
const OVERRIDE_HEADER: &str = "\
-- ~/.config/tezca/keybinds.lua — generated by `tezca keybind`. Do not hand-edit.
--
-- Loaded by hyprland.lua AFTER conf.d/keybinds.lua, so these win. Each entry
-- releases the shipped combo with `hl.unbind` and binds the replacement; the
-- `was=` note records which shipped bind it replaced, so a later upstream change
-- to keybinds.lua is reported as stale instead of silently rebinding the wrong
-- key.
--
-- Combos are written as literal strings even where the shipped map builds them
-- from the `mod` variable: `hl.unbind` matches on the exact registered string
-- (and is case-sensitive), and `mod .. \" + Q\"` registers precisely \"SUPER + Q\".
--
-- `tezca keybind restore` undoes the last change; `tezca keybind reset` drops all
-- of them and returns to the shipped map. For extra binds of your own that Tezca
-- should never touch, use conf.d/local.lua.
";

/// The shipped bind map. Read-only — nothing in this module writes to it.
fn base_path() -> Result<PathBuf, String> {
    Ok(repo::config_home()?.join("hypr").join("conf.d").join("keybinds.lua"))
}

/// The generated override layer.
fn override_path() -> Result<PathBuf, String> {
    Ok(repo::config_home()?.join("tezca").join("keybinds.lua"))
}

/// Snapshot of the override layer taken before every write, for `restore`.
fn backup_path() -> Result<PathBuf, String> {
    let base = std::env::var_os("XDG_CACHE_HOME")
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty())
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".cache")))
        .ok_or("neither $XDG_CACHE_HOME nor $HOME is set")?;
    Ok(base.join("tezca").join("backups").join("keybind-overrides.prev"))
}

/// Create the override file if absent, so Hyprland's `source` never errors on a
/// fresh install. Returns whether it created anything. Called by `tezca link`.
pub fn seed() -> Result<bool, String> {
    let p = override_path()?;
    if p.exists() {
        return Ok(false);
    }
    atomic::write(&p, OVERRIDE_HEADER)?;
    Ok(true)
}

pub fn run(args: &[&str]) -> i32 {
    let r = match args.first().copied() {
        None | Some("list") => cmd_list(args.get(1..).unwrap_or(&[])),
        Some("rebind") => return cmd_rebind(&args[1..]),
        Some("set-action") => cmd_set_action(&args[1..]),
        Some("restore") => cmd_restore(),
        Some("reset") => cmd_reset(),
        Some("-h") | Some("--help") => {
            print_help();
            Ok(())
        }
        Some(other) => Err(format!(
            "unknown keybind subcommand: {other}\n  try: list · rebind --line N … · \
             set-action --line N … · restore · reset"
        )),
    };
    match r {
        Ok(()) => 0,
        Err(e) => {
            eprintln!("{} {e}", term::red("error:"));
            1
        }
    }
}

// ---------------------------------------------------------------------------
// Parsing the shipped map
// ---------------------------------------------------------------------------

/// A parsed bind (1-based `line` in the shipped map).
#[derive(Clone, Debug, PartialEq)]
struct Bind {
    line: usize,
    /// The Lua options table verbatim (`{ locked = true, repeating = true }`),
    /// or "" when the bind takes none. This replaces hyprlang's `bind`/`binde`/
    /// `bindl`/`bindel`/`bindm` keyword suffixes, which all became flags here.
    opts: String,
    mods: String, // normalized, always spelled SUPER (never the `mod` variable)
    key: String,
    desc: String, // trailing `-- comment`, or "" if undocumented
    /// The dispatcher expression, e.g. `hl.dsp.exec_cmd("uwsm app -- brave")`.
    /// Empty marks a bind whose call spans several lines (a `function() … end`
    /// body), which this line-oriented reader cannot capture or reproduce.
    action: String,
    /// True when an override-layer entry replaced this bind.
    overridden: bool,
}

/// Split a Lua argument list on top-level commas, ignoring those nested in
/// parentheses, braces or string literals. Returns the arguments plus the byte
/// offset just past the `)` that closed the call, so the caller can find the
/// trailing comment without rescanning.
///
/// Returns None if the list does not close on this line — a multi-line
/// `hl.bind(…, function() …` call.
///
/// Scanning is required rather than a `find("--")`: `hl.dsp.exec_cmd("uwsm app
/// -- dolphin")` puts a comment marker inside a string on most of these lines,
/// and splitting there would truncate the dispatcher and lose the description.
fn split_lua_args(s: &str) -> Option<(Vec<String>, usize)> {
    let (mut depth, mut in_str, mut esc) = (0i32, false, false);
    let (mut args, mut cur) = (Vec::new(), String::new());
    for (i, c) in s.char_indices() {
        if in_str {
            cur.push(c);
            match c {
                _ if esc => esc = false,
                '\\' => esc = true,
                '"' => in_str = false,
                _ => {}
            }
            continue;
        }
        match c {
            '"' => {
                in_str = true;
                cur.push(c);
            }
            '(' | '{' | '[' => {
                depth += 1;
                cur.push(c);
            }
            ')' | '}' | ']' if depth > 0 => {
                depth -= 1;
                cur.push(c);
            }
            // The unmatched ')' that closes `hl.bind(` itself.
            ')' => {
                args.push(cur.trim().to_string());
                return Some((args, i + c.len_utf8()));
            }
            ',' if depth == 0 => {
                args.push(cur.trim().to_string());
                cur.clear();
            }
            _ => cur.push(c),
        }
    }
    None
}

/// The `-- comment` at the end of a line, ignoring `--` inside string literals
/// (`hl.dsp.exec_cmd("uwsm app -- dolphin")`). Empty when there is none.
fn trailing_comment(s: &str) -> String {
    let (mut in_str, mut esc) = (false, false);
    let b: Vec<char> = s.chars().collect();
    for i in 0..b.len() {
        if in_str {
            match b[i] {
                _ if esc => esc = false,
                '\\' => esc = true,
                '"' => in_str = false,
                _ => {}
            }
            continue;
        }
        if b[i] == '"' {
            in_str = true;
        } else if b[i] == '-' && b.get(i + 1) == Some(&'-') {
            return b[i + 2..].iter().collect::<String>().trim().to_string();
        }
    }
    String::new()
}

/// Recover "SUPER SHIFT" + "left" from a combo argument, which is either a
/// literal `"CTRL + Q"` or the shipped map's `mod .. " + SHIFT + left"`.
fn parse_combo_arg(arg: &str) -> Option<(String, String)> {
    let a = arg.trim();
    let text = match a.strip_prefix("mod") {
        // `mod .. " + X"` registers the string "SUPER + X", so that is what the
        // override layer has to unbind — expand it rather than keep the variable.
        Some(rest) => {
            let lit = rest.trim().strip_prefix("..")?.trim();
            let inner = lit.strip_prefix('"')?.strip_suffix('"')?;
            format!("SUPER{inner}")
        }
        None => a.strip_prefix('"')?.strip_suffix('"')?.to_string(),
    };
    let mut parts: Vec<&str> = text.split('+').map(str::trim).filter(|p| !p.is_empty()).collect();
    let key = parts.pop()?.to_string();
    Some((parts.join(" "), key))
}

/// Parse `hl.bind(<combo>, <dispatcher>[, <opts>])  -- desc` — None if not a bind.
fn parse_bind(no: usize, raw: &str) -> Option<Bind> {
    let line = raw.trim();
    let rest = line.strip_prefix("hl.bind(")?;

    match split_lua_args(rest) {
        Some((args, end)) => {
            let (mods, key) = parse_combo_arg(args.first()?)?;
            let desc = rest[end..]
                .trim_start()
                .strip_prefix("--")
                .map(|d| d.trim().to_string())
                .unwrap_or_default();
            Some(Bind {
                line: no,
                opts: args.get(2).cloned().unwrap_or_default(),
                mods,
                key,
                desc,
                action: args.get(1).cloned().unwrap_or_default(),
                overridden: false,
            })
        }
        // Multi-line call: the combo is still on this line and is what `list`
        // and conflict detection need, but the body is not reproducible. The
        // description still has to be picked up, or the bind vanishes from
        // `list` entirely (which filters undocumented binds) instead of showing
        // up as present-but-not-rebindable.
        None => {
            let (mods, key) = parse_combo_arg(rest.split_once(',')?.0)?;
            Some(Bind {
                line: no,
                opts: String::new(),
                mods,
                key,
                desc: trailing_comment(rest),
                action: String::new(),
                overridden: false,
            })
        }
    }
}

/// "-- ==== Title ====" / "-- ---- Title ----" → the inner Title.
fn section_title(line: &str) -> Option<String> {
    let c = line.trim().strip_prefix("--")?.trim();
    let first = c.as_bytes().first().copied()?;
    if first != b'=' && first != b'-' {
        return None;
    }
    let inner = c.trim_matches(|ch| ch == '=' || ch == '-' || ch == ' ');
    (!inner.is_empty()).then(|| inner.to_string())
}

// ---------------------------------------------------------------------------
// The override layer
// ---------------------------------------------------------------------------

/// One entry of the override layer: what line N of the shipped map became.
#[derive(Clone, Debug, PartialEq)]
struct Ovr {
    line: usize,
    /// The shipped combo this entry replaced, recorded so a later upstream change
    /// to `keybinds.lua` is detected instead of silently misapplied.
    was_mods: String,
    was_key: String,
    opts: String,
    mods: String,
    key: String,
    action: String,
    desc: String,
}

/// `# @42 was=$mod|W` — the entry header. `|` separates the recorded combo, so a
/// comma in neither field can be ambiguous, and an empty modifier list is legal
/// (`was=|XF86AudioMute`) because plenty of media binds have no modifier.
fn parse_ovr_header(line: &str) -> Option<(usize, String, String)> {
    let rest = line.trim().strip_prefix("-- @")?;
    let (num, was) = rest.split_once(" was=")?;
    let n: usize = num.trim().parse().ok()?;
    let (mods, key) = was.split_once('|')?;
    Some((n, mods.trim().to_string(), key.trim().to_string()))
}

/// Parse the override layer out of already-read text.
fn parse_overrides(text: &str) -> Vec<Ovr> {
    let mut out: Vec<Ovr> = Vec::new();
    let mut pending: Option<(usize, String, String)> = None;
    for raw in text.lines() {
        if let Some(h) = parse_ovr_header(raw) {
            pending = Some(h);
            continue;
        }
        let Some((line, was_mods, was_key)) = pending.clone() else { continue };
        // `parse_bind`'s line argument is only a label here; the header is the key.
        if let Some(b) = parse_bind(line, raw) {
            out.push(Ovr {
                line,
                was_mods,
                was_key,
                opts: b.opts,
                mods: b.mods,
                key: b.key,
                action: b.action,
                desc: b.desc,
            });
            pending = None;
        }
    }
    out
}

/// Read the override layer. A missing file simply means "no overrides".
fn load_overrides() -> Result<Vec<Ovr>, String> {
    let p = override_path()?;
    Ok(fs::read_to_string(&p).map(|t| parse_overrides(&t)).unwrap_or_default())
}

/// Serialize the override layer.
///
/// Every `unbind` is emitted before every `bind`: interleaved, moving a combo from
/// one bind to another would have the donor's `unbind` cancel the recipient's new
/// `bind` whenever the donor sorted later.
fn render_overrides(ovrs: &[Ovr]) -> String {
    let mut s = String::from(OVERRIDE_HEADER);
    if ovrs.is_empty() {
        return s;
    }
    let mut sorted = ovrs.to_vec();
    sorted.sort_by_key(|o| o.line);

    s.push_str("\n-- --- release the shipped combos being replaced ---\n");
    for o in &sorted {
        s.push_str(&format!(
            "hl.unbind(\"{}\")\n",
            format_combo(&display_mods(&o.was_mods), &o.was_key)
        ));
    }
    s.push_str("\n-- --- replacements ---\n");
    for o in &sorted {
        let comment = if o.desc.is_empty() { String::new() } else { format!("  -- {}", o.desc) };
        let opts = if o.opts.is_empty() { String::new() } else { format!(", {}", o.opts) };
        s.push_str(&format!("-- @{} was={}|{}\n", o.line, o.was_mods, o.was_key));
        s.push_str(&format!(
            "hl.bind(\"{}\", {}{}){}\n",
            format_combo(&display_mods(&o.mods), &o.key),
            o.action,
            opts,
            comment
        ));
    }
    s
}

/// Write the override layer, snapshotting the previous contents for `restore`.
fn save_overrides(ovrs: &[Ovr]) -> Result<(), String> {
    let p = override_path()?;
    let previous = fs::read_to_string(&p).unwrap_or_else(|_| OVERRIDE_HEADER.to_string());
    atomic::write(&backup_path()?, &previous)?;
    atomic::write(&p, &render_overrides(ovrs))
}

/// Apply the override layer to the shipped map.
///
/// An entry whose recorded `was=` combo no longer matches line N is **stale** —
/// the shipped map changed underneath it — so it is skipped and reported rather
/// than applied to whatever bind now occupies that line.
fn apply_overrides(base: &str, ovrs: &[Ovr]) -> (Vec<Bind>, Vec<Ovr>) {
    let mut binds = Vec::new();
    let mut stale = Vec::new();
    for (i, raw) in base.lines().enumerate() {
        let Some(mut b) = parse_bind(i + 1, raw) else { continue };
        if let Some(o) = ovrs.iter().find(|o| o.line == b.line) {
            if same_combo(&b.mods, &b.key, &o.was_mods, &o.was_key) {
                b.mods = o.mods.clone();
                b.key = o.key.clone();
                b.action = o.action.clone();
                b.desc = if o.desc.is_empty() { b.desc } else { o.desc.clone() };
                b.overridden = true;
            } else {
                stale.push(o.clone());
            }
        }
        binds.push(b);
    }
    (binds, stale)
}

/// The effective bind map: shipped, with overrides applied.
fn effective() -> Result<(Vec<Bind>, Vec<Ovr>), String> {
    let base =
        fs::read_to_string(base_path()?).map_err(|e| format!("cannot read keybinds.lua: {e}"))?;
    let ovrs = load_overrides()?;
    Ok(apply_overrides(&base, &ovrs))
}

fn warn_stale(stale: &[Ovr]) {
    for o in stale {
        eprintln!(
            "  {} the override for line {} no longer matches the shipped map \
             (it recorded {}) — ignoring it; re-apply it from Settings",
            term::yellow("!"),
            o.line,
            format_combo(&o.was_mods, &o.was_key)
        );
    }
}

// ---------------------------------------------------------------------------
// list
// ---------------------------------------------------------------------------

/// `tezca keybind list [--machine]` — documented binds with line numbers.
/// Machine format:  `S\t<title>`  for a section,
/// `B\t<line>\t<mods>\t<key>\t<desc>\t<action>\t<overridden 0|1>` for a bind.
/// The trailing field is appended, so a parser that reads five fields and ignores
/// the rest keeps working.
fn cmd_list(args: &[&str]) -> Result<(), String> {
    let base =
        fs::read_to_string(base_path()?).map_err(|e| format!("cannot read keybinds.lua: {e}"))?;
    let (binds, stale) = apply_overrides(&base, &load_overrides()?);
    let machine = args.iter().any(|a| *a == "--machine" || *a == "-m");
    if !machine {
        warn_stale(&stale);
    }

    for (i, raw) in base.lines().enumerate() {
        if let Some(title) = section_title(raw) {
            if machine {
                println!("S\t{title}");
            } else {
                println!("\n{}", term::bold(&title));
            }
            continue;
        }
        let Some(b) = binds.iter().find(|b| b.line == i + 1) else { continue };
        if b.desc.is_empty() {
            continue; // only surface documented binds
        }
        if machine {
            println!(
                "B\t{}\t{}\t{}\t{}\t{}\t{}",
                b.line,
                b.mods,
                b.key,
                b.desc,
                b.action,
                u8::from(b.overridden)
            );
        } else {
            let combo = format_combo(&b.mods, &b.key);
            let mark = if b.overridden { term::cyan("*") } else { " ".to_string() };
            println!("{mark} {:<24} {}", combo, term::dim(&b.desc));
        }
    }
    Ok(())
}

fn format_combo(mods: &str, key: &str) -> String {
    let mut parts: Vec<&str> = mods.split_whitespace().collect();
    if !key.is_empty() {
        parts.push(key);
    }
    parts.join(" + ")
}

// ---------------------------------------------------------------------------
// rebind
// ---------------------------------------------------------------------------

/// Returns a process exit code directly (2 = conflict, for the GUI to detect).
fn cmd_rebind(args: &[&str]) -> i32 {
    match rebind(args) {
        Ok(()) => 0,
        Err(RebindErr::Conflict(msg)) => {
            eprintln!("conflict: {msg}");
            2
        }
        Err(RebindErr::Other(e)) => {
            eprintln!("{} {e}", term::red("error:"));
            1
        }
    }
}

enum RebindErr {
    Conflict(String),
    Other(String),
}
impl From<String> for RebindErr {
    fn from(s: String) -> Self {
        RebindErr::Other(s)
    }
}

fn rebind(args: &[&str]) -> Result<(), RebindErr> {
    let mut line: Option<usize> = None;
    let mut mods = String::new();
    let mut key = String::new();
    let mut expect_mods: Option<String> = None;
    let mut expect_key: Option<String> = None;
    let mut force = false;

    let mut it = args.iter().copied();
    while let Some(a) = it.next() {
        match a {
            "--line" => line = it.next().and_then(|v| v.parse().ok()),
            "--mods" => mods = it.next().unwrap_or("").to_string(),
            "--key" => key = it.next().unwrap_or("").to_string(),
            "--expect-mods" => expect_mods = it.next().map(str::to_string),
            "--expect-key" => expect_key = it.next().map(str::to_string),
            "--force" => force = true,
            other => return Err(format!("unknown flag: {other}").into()),
        }
    }
    let line = line.ok_or_else(|| "rebind needs --line N".to_string())?;

    // Validate before anything is read or written: both values are formatted
    // verbatim into a config line.
    validate::keybind_mods(&mods)?;
    validate::keybind_key(&key)?;

    let (binds, stale) = effective()?;
    warn_stale(&stale);
    let target = binds
        .iter()
        .find(|b| b.line == line)
        .ok_or_else(|| format!("line {line} is not a bind line"))?
        .clone();
    reject_hold_bind(&target)?;

    // Guard: the bind must still carry the combo the GUI showed us — compared
    // against the *effective* combo, since that is what was displayed.
    if let (Some(em), Some(ek)) = (&expect_mods, &expect_key) {
        if !same_combo(&target.mods, &target.key, em, ek) {
            return Err("the keybindings changed since they were read — reopen Settings \
                        and try again"
                .to_string()
                .into());
        }
    }

    // Conflict check against every other bind, as it effectively stands.
    if !force {
        if let Some(other) = conflict(&binds, line, &mods, &key) {
            let what =
                if other.desc.is_empty() { format!("line {}", other.line) } else { other.desc };
            return Err(RebindErr::Conflict(format!(
                "{} is already bound to {what}",
                format_combo(&display_mods(&mods), &normalize_key(&key))
            )));
        }
    }

    // Read the shipped combo straight from the base map: that is what the override
    // has to release, and it stays correct across repeated rebinds.
    let base_bind = shipped(line)?;
    let ovr = Ovr {
        line,
        was_mods: base_bind.mods.clone(),
        was_key: base_bind.key.clone(),
        opts: base_bind.opts.clone(),
        mods: display_mods(&mods),
        key: normalize_key(&key),
        // Carry the effective action/desc, so a previous `set-action` is not lost.
        action: target.action.clone(),
        desc: target.desc.clone(),
    };
    commit(ovr, &base_bind)?;

    println!(
        "  {} {} → {}",
        term::green("✓"),
        term::dim(&format!("line {line}")),
        format_combo(&display_mods(&mods), &normalize_key(&key))
    );
    Ok(())
}

/// A hold-bind — hyprlang's `bindm`, now the `mouse = true` flag. Hyprland's
/// `unbind` does not release one, so an override would leave both the old and
/// the new binding active.
fn is_hold_bind(b: &Bind) -> bool {
    b.opts.contains("mouse")
}

/// Refuse to override what cannot be reproduced or released.
fn reject_hold_bind(b: &Bind) -> Result<(), String> {
    if is_hold_bind(b) {
        return Err(format!(
            "line {} is a `mouse = true` hold-bind, which cannot be overridden \
             (Hyprland's `hl.unbind` does not release mouse/hold binds) — \
             edit conf.d/keybinds.lua directly",
            b.line
        ));
    }
    if b.action.is_empty() {
        return Err(format!(
            "line {} is a multi-line bind (a `function() … end` body), which \
             cannot be reproduced in the override layer — \
             edit conf.d/keybinds.lua directly",
            b.line
        ));
    }
    Ok(())
}

/// The first *other* bind that already uses this combo.
fn conflict(binds: &[Bind], skip_line: usize, mods: &str, key: &str) -> Option<Bind> {
    binds
        .iter()
        .find(|b| {
            if b.line == skip_line {
                return false;
            }
            // Hold-binds live in their own namespace, so sharing a combo with one
            // is not a conflict — that is how `$mod+Z` doubles as hold-to-move.
            if is_hold_bind(b) {
                return false;
            }
            same_combo(&b.mods, &b.key, mods, key)
        })
        .cloned()
}

/// The bind exactly as shipped, ignoring the override layer.
fn shipped(line: usize) -> Result<Bind, String> {
    let base =
        fs::read_to_string(base_path()?).map_err(|e| format!("cannot read keybinds.lua: {e}"))?;
    base.lines()
        .enumerate()
        .find_map(|(i, raw)| (i + 1 == line).then(|| parse_bind(line, raw)).flatten())
        .ok_or_else(|| format!("line {line} is not a bind line"))
}

/// Upsert an override — or drop it, when it would only restate the shipped bind.
fn commit(ovr: Ovr, base_bind: &Bind) -> Result<(), String> {
    let mut ovrs = load_overrides()?;
    ovrs.retain(|o| o.line != ovr.line);
    if !restates_shipped(&ovr, base_bind) {
        ovrs.push(ovr);
    }
    save_overrides(&ovrs)?;
    if hypr::in_session() {
        let _ = hypr::reload();
    }
    Ok(())
}

/// True when an override would say exactly what the shipped map already says, so
/// returning a key to its default leaves a clean override layer behind.
fn restates_shipped(o: &Ovr, base: &Bind) -> bool {
    same_combo(&o.mods, &o.key, &base.mods, &base.key)
        && o.action == base.action
        && o.desc == base.desc
}

// ---------------------------------------------------------------------------
// set-action  (change what a bind does — dispatcher + args)
// ---------------------------------------------------------------------------

/// `tezca keybind set-action --line N --action "exec, uwsm app -- firefox.desktop"
/// [--desc "Firefox"] [--expect-mods … --expect-key …]` — change one bind's
/// dispatcher+args (and optionally its label), keeping its combo.
fn cmd_set_action(args: &[&str]) -> Result<(), String> {
    let mut line: Option<usize> = None;
    let mut action: Option<String> = None;
    let mut desc: Option<String> = None;
    let mut expect_mods: Option<String> = None;
    let mut expect_key: Option<String> = None;

    let mut it = args.iter().copied();
    while let Some(a) = it.next() {
        match a {
            "--line" => line = it.next().and_then(|v| v.parse().ok()),
            "--action" => action = it.next().map(str::to_string),
            "--desc" => desc = it.next().map(str::to_string),
            "--expect-mods" => expect_mods = it.next().map(str::to_string),
            "--expect-key" => expect_key = it.next().map(str::to_string),
            other => return Err(format!("unknown flag: {other}")),
        }
    }
    let line = line.ok_or("set-action needs --line N")?;
    let action = action.ok_or("set-action needs --action")?.trim().to_string();

    validate::keybind_action(&action)?;
    if let Some(d) = &desc {
        validate::keybind_desc(d)?;
    }

    let (binds, stale) = effective()?;
    warn_stale(&stale);
    let target = binds
        .iter()
        .find(|b| b.line == line)
        .ok_or_else(|| format!("line {line} is not a bind line"))?
        .clone();
    reject_hold_bind(&target)?;

    if let (Some(em), Some(ek)) = (&expect_mods, &expect_key) {
        if !same_combo(&target.mods, &target.key, em, ek) {
            return Err(
                "the keybindings changed since they were read — reopen Settings and try again"
                    .into(),
            );
        }
    }

    let base_bind = shipped(line)?;
    let ovr = Ovr {
        line,
        was_mods: base_bind.mods.clone(),
        was_key: base_bind.key.clone(),
        opts: base_bind.opts.clone(),
        // Keep the combo as it effectively stands, so a previous rebind survives.
        mods: target.mods.clone(),
        key: target.key.clone(),
        action: action.clone(),
        desc: desc.filter(|s| !s.is_empty()).unwrap_or_else(|| target.desc.clone()),
    };
    commit(ovr, &base_bind)?;

    println!("  {} {} → {}", term::green("✓"), term::dim(&format!("line {line}")), action);
    Ok(())
}

fn cmd_restore() -> Result<(), String> {
    let bak = backup_path()?;
    let text = fs::read_to_string(&bak)
        .map_err(|_| "no snapshot to restore (change a keybinding first)".to_string())?;
    atomic::write(&override_path()?, &text)?;
    if hypr::in_session() {
        let _ = hypr::reload();
    }
    println!("  {} undid the last keybinding change", term::green("✓"));
    Ok(())
}

fn cmd_reset() -> Result<(), String> {
    let n = load_overrides()?.len();
    save_overrides(&[])?;
    if hypr::in_session() {
        let _ = hypr::reload();
    }
    println!("  {} dropped {n} override(s) — back to the shipped keybindings", term::green("✓"));
    Ok(())
}

// ---------------------------------------------------------------------------
// Combo helpers
// ---------------------------------------------------------------------------

/// Canonical modifier set for *comparison*: $mod→SUPER, uppercased, sorted,
/// de-duplicated. Plain alphabetical order, so two spellings of the same combo
/// compare equal (`$mod SHIFT ALT` and `$mod ALT SHIFT` both appear in the
/// shipped map).
fn normalize_mods(mods: &str) -> String {
    let mut parts: Vec<String> =
        mods.replace("$mod", "SUPER").split_whitespace().map(|s| s.to_uppercase()).collect();
    parts.sort();
    parts.dedup();
    parts.join(" ")
}

/// Canonical modifier set for *display and storage*: the Tezca modifier first,
/// then the rest alphabetically.
///
/// Distinct from [`normalize_mods`] on purpose. Sorting plain-alphabetically is
/// what makes two spellings compare equal, but it also renders `SUPER SHIFT` as
/// `SHIFT $mod`, which reads backwards next to the shipped map's `$mod SHIFT`.
/// Keeping the two apart also makes the override layer round-trip byte-for-byte:
/// what we store is exactly what re-parsing the file gives back.
fn display_mods(mods: &str) -> String {
    let canonical = normalize_mods(mods);
    let mut parts: Vec<&str> = canonical.split_whitespace().collect();
    parts.sort_by_key(|m| (*m != "SUPER", *m));
    parts.join(" ")
}

/// Tidy a key for writing: single letter → uppercase, arrows → lowercase.
fn normalize_key(key: &str) -> String {
    let k = key.trim();
    if k.len() == 1 && k.chars().all(|c| c.is_ascii_alphabetic()) {
        return k.to_uppercase();
    }
    match k.to_lowercase().as_str() {
        "left" | "right" | "up" | "down" => k.to_lowercase(),
        _ => k.to_string(),
    }
}

/// Do two combos mean the same bind? (order-independent mods, case-fold key).
fn same_combo(mods_a: &str, key_a: &str, mods_b: &str, key_b: &str) -> bool {
    normalize_mods(mods_a) == normalize_mods(mods_b)
        && key_a.trim().eq_ignore_ascii_case(key_b.trim())
}

fn print_help() {
    println!("{}", term::header("tezca keybind"));
    println!("{}", term::dim("  changes go to ~/.config/tezca/keybinds.conf;"));
    println!("{}", term::dim("  the shipped conf.d/keybinds.conf is never modified"));
    println!();
    println!(
        "  {}                    list effective binds (* = overridden)",
        term::cyan("list [--machine]")
    );
    println!(
        "  {}  rebind a line's combo",
        term::cyan("rebind --line N --mods \"SUPER SHIFT\" --key W")
    );
    println!(
        "  {}  change what a bind does",
        term::cyan("set-action --line N --action \"exec, uwsm app -- app.desktop\"")
    );
    println!("  {}                         undo the last change", term::cyan("restore"));
    println!("  {}                           drop every override", term::cyan("reset"));
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A trimmed stand-in for the shipped map, carrying the shapes that actually
    /// appear in it: literal and `mod ..` combos, bare and flagged binds, a
    /// hold-bind, a dispatcher whose argument contains both `--` and a comma,
    /// and a multi-line `function()` bind.
    const BASE: &str = r#"
-- ==== Windows ====
hl.bind("CTRL + Q",    hl.dsp.window.close())                       -- close focused window
hl.bind(mod .. " + W", hl.dsp.exec_cmd("uwsm app -- brave"))        -- Browser
hl.bind(mod .. " + C", hl.dsp.exec_cmd("code"), { repeating = true }) -- Editor
hl.bind(mod .. " + Z", hl.dsp.window.drag(), { mouse = true })      -- hold to move
-- ---- Media ----
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SINK@ toggle"), { locked = true })  -- Mute
hl.bind(mod .. " + SHIFT + left", hl.dsp.window.resize({ x = -40, y = 0, relative = true }), { repeating = true }) -- Shrink
hl.bind("ALT + Tab", function()                                     -- cycle focus
    hl.dispatch(hl.dsp.window.cycle_next())
end)
hl.bind(mod .. " + T", hl.dsp.exec_cmd("alacritty"))                -- Terminal
hl.bind(mod .. " + U", hl.dsp.exec_cmd("undocumented-no-desc"))
"#;

    fn base_binds() -> Vec<Bind> {
        apply_overrides(BASE, &[]).0
    }

    fn at(line: usize) -> Bind {
        base_binds().into_iter().find(|b| b.line == line).unwrap()
    }

    /// An override of `line`, keeping the shipped action/desc.
    fn ovr(line: usize, mods: &str, key: &str) -> Ovr {
        let b = at(line);
        Ovr {
            line,
            was_mods: b.mods.clone(),
            was_key: b.key.clone(),
            opts: b.opts,
            mods: mods.to_string(),
            key: key.to_string(),
            action: b.action,
            desc: b.desc,
        }
    }

    #[test]
    fn parses_both_combo_spellings_and_keeps_the_dispatcher_whole() {
        // `mod .. " + W"` registers "SUPER + W", so it must normalize to SUPER —
        // that is the string `hl.unbind` will have to match.
        let brave = at(4);
        assert_eq!(brave.mods, "SUPER");
        assert_eq!(brave.key, "W");
        assert_eq!(brave.desc, "Browser");
        // The `--` inside the command must not be mistaken for the comment.
        assert_eq!(brave.action, r#"hl.dsp.exec_cmd("uwsm app -- brave")"#);
        assert_eq!(brave.opts, "");

        // A literal combo with no `mod` prefix.
        let close = at(3);
        assert_eq!((close.mods.as_str(), close.key.as_str()), ("CTRL", "Q"));

        // A bind with no modifier at all parses with an empty mods field, and
        // its flags land in `opts`.
        let mute = at(8);
        assert_eq!(mute.mods, "");
        assert_eq!(mute.key, "XF86AudioMute");
        assert_eq!(mute.opts, "{ locked = true }");
    }

    #[test]
    fn a_comma_inside_the_dispatcher_does_not_split_the_arguments() {
        // `resize({ x = -40, y = 0, relative = true })` has three commas nested
        // inside braces; splitting on any of them would truncate the action and
        // put garbage in the options slot.
        let shrink = at(9);
        assert_eq!(shrink.mods, "SUPER SHIFT");
        assert_eq!(shrink.key, "left");
        assert_eq!(shrink.action, "hl.dsp.window.resize({ x = -40, y = 0, relative = true })");
        assert_eq!(shrink.opts, "{ repeating = true }");
        assert_eq!(shrink.desc, "Shrink");
    }

    #[test]
    fn a_multiline_function_bind_is_listed_but_refused_for_rebinding() {
        let tab = at(10);
        assert_eq!((tab.mods.as_str(), tab.key.as_str()), ("ALT", "Tab"));
        assert_eq!(tab.action, "", "an unreproducible body must not be invented");
        // The description still has to survive, or `list` (which filters
        // undocumented binds) would hide the bind rather than show it as
        // present-but-not-rebindable.
        assert_eq!(tab.desc, "cycle focus");
        let e = reject_hold_bind(&tab).unwrap_err();
        assert!(e.contains("multi-line"), "{e}");
    }

    #[test]
    fn a_comment_marker_inside_a_string_is_not_a_comment() {
        assert_eq!(trailing_comment(r#""x", hl.dsp.exec_cmd("uwsm app -- brave")"#), "");
        assert_eq!(
            trailing_comment(r#""x", hl.dsp.exec_cmd("uwsm app -- brave")) -- Browser"#),
            "Browser"
        );
        assert_eq!(trailing_comment(r#""x", hl.dsp.window.close())"#), "");
    }

    #[test]
    fn a_hold_bind_is_detected_from_its_mouse_flag() {
        let hold = at(6);
        assert!(is_hold_bind(&hold));
        assert!(reject_hold_bind(&hold).unwrap_err().contains("hold-bind"));
    }

    #[test]
    fn finds_section_titles_in_both_styles() {
        assert_eq!(section_title("-- ==== Windows ====").as_deref(), Some("Windows"));
        assert_eq!(section_title("-- ---- Media ----").as_deref(), Some("Media"));
        assert_eq!(section_title("-- a normal comment"), None);
        assert_eq!(section_title(r#"hl.bind("SUPER + W", hl.dsp.exec_cmd("x"))"#), None);
    }

    #[test]
    fn an_override_replaces_the_combo_but_keeps_the_action() {
        let (binds, stale) = apply_overrides(BASE, &[ovr(4, "SUPER SHIFT", "W")]);
        assert!(stale.is_empty());
        let b = binds.iter().find(|b| b.line == 4).unwrap();
        assert_eq!(b.mods, "SUPER SHIFT");
        assert_eq!(
            b.action,
            r#"hl.dsp.exec_cmd("uwsm app -- brave")"#,
            "the action must survive a rebind"
        );
        assert!(b.overridden);
        assert!(!binds.iter().filter(|b| b.line != 4).any(|b| b.overridden));
    }

    #[test]
    fn a_stale_override_is_reported_and_the_shipped_bind_stands() {
        // The shipped map changed under the override: line 4 is no longer SUPER+W.
        let mut o = ovr(4, "SUPER SHIFT", "W");
        o.was_key = "Q".to_string();
        let (binds, stale) = apply_overrides(BASE, &[o]);
        assert_eq!(stale.len(), 1, "the mismatch must be surfaced");
        let b = binds.iter().find(|b| b.line == 4).unwrap();
        assert_eq!(b.key, "W");
        assert!(!b.overridden);
    }

    #[test]
    fn every_unbind_is_emitted_before_every_bind() {
        // Move SUPER+T (line 13) onto SUPER+W, and SUPER+W (line 4) elsewhere. If
        // the unbind for line 13 came after line 4's replacement, it would cancel
        // it and the combo would end up bound to nothing.
        let out = render_overrides(&[ovr(13, "SUPER", "W"), ovr(4, "SUPER SHIFT", "B")]);
        let last_unbind = out.rfind("\nhl.unbind(").expect("unbinds present");
        let first_bind = out.find("\nhl.bind(").expect("binds present");
        assert!(last_unbind < first_bind, "all unbinds must precede all binds:\n{out}");
    }

    #[test]
    fn the_override_layer_round_trips_through_render_and_parse() {
        let a = ovr(4, "SUPER SHIFT", "B");
        // An empty modifier list has to survive the `was=|Key` encoding.
        let b = ovr(8, "", "XF86AudioMute");
        let parsed = parse_overrides(&render_overrides(&[a.clone(), b.clone()]));
        assert_eq!(parsed, vec![a, b]);
    }

    #[test]
    fn a_hold_bind_cannot_be_overridden() {
        let e = reject_hold_bind(&at(6)).unwrap_err();
        assert!(e.contains("hold-bind"), "{e}");
        assert!(reject_hold_bind(&at(4)).is_ok());
    }

    #[test]
    fn a_hold_bind_sharing_a_combo_is_not_a_conflict_but_a_real_bind_is() {
        let binds = base_binds();
        // A hold-bind is its own namespace: rebinding onto SUPER+Z is allowed.
        assert!(conflict(&binds, 4, "SUPER", "Z").is_none());
        // A plain bind that already owns the combo is a real conflict.
        let c = conflict(&binds, 4, "SUPER", "T").expect("SUPER+T is the terminal bind");
        assert_eq!(c.desc, "Terminal");
        // Rebinding a line onto its own current combo is not a conflict.
        assert!(conflict(&binds, 4, "SUPER", "W").is_none());
    }

    #[test]
    fn conflict_detection_sees_through_the_override_layer() {
        // Line 13 has been moved off SUPER+T, so SUPER+T is free for line 4 now…
        let (binds, _) = apply_overrides(BASE, &[ovr(13, "SUPER ALT", "T")]);
        assert!(conflict(&binds, 4, "SUPER", "T").is_none());
        // …and its new combo is the one that is taken.
        assert!(conflict(&binds, 4, "SUPER ALT", "T").is_some());
    }

    #[test]
    fn an_override_that_restates_the_shipped_bind_is_dropped() {
        let base = at(4);
        let restated = Ovr {
            line: 4,
            was_mods: base.mods.clone(),
            was_key: base.key.clone(),
            opts: base.opts.clone(),
            mods: display_mods("SUPER"),
            key: normalize_key("w"),
            action: base.action.clone(),
            desc: base.desc.clone(),
        };
        assert!(restates_shipped(&restated, &base), "a rebind back to SUPER+W is the default");

        let moved = ovr(4, "SUPER SHIFT", "W");
        assert!(!restates_shipped(&moved, &base));
    }

    #[test]
    fn combos_compare_independently_of_modifier_order_and_key_case() {
        assert!(same_combo("SUPER SHIFT", "W", "SHIFT SUPER", "w"));
        assert!(same_combo("$mod", "W", "SUPER", "W"));
        assert!(!same_combo("SUPER", "W", "SUPER SHIFT", "W"));
        assert!(!same_combo("SUPER", "W", "SUPER", "Q"));
    }

    #[test]
    fn writes_super_back_out_in_the_house_style() {
        // The override layer spells combos out in full: `hl.unbind` matches the
        // registered string exactly, and SUPER must lead so the rendered string
        // matches what `mod .. " + …"` produced in the shipped map.
        assert_eq!(format_combo(&display_mods("SUPER SHIFT"), "W"), "SUPER + SHIFT + W");
        assert_eq!(
            format_combo(&display_mods("SHIFT SUPER"), "W"),
            "SUPER + SHIFT + W",
            "input order must not matter"
        );
        assert_eq!(format_combo(&display_mods(""), "XF86AudioMute"), "XF86AudioMute");
        // Comparison order stays plain-alphabetical so equal combos compare equal.
        assert_eq!(normalize_mods("SUPER SHIFT"), "SHIFT SUPER");
        assert_eq!(normalize_key("w"), "W");
        assert_eq!(normalize_key("Left"), "left");
        assert_eq!(normalize_key("XF86AudioMute"), "XF86AudioMute");
    }

    #[test]
    fn an_empty_override_layer_renders_to_just_the_header() {
        let out = render_overrides(&[]);
        assert_eq!(out, OVERRIDE_HEADER);
        // The header prose mentions `unbind`; what must be absent is a directive.
        assert!(!out.lines().any(|l| l.starts_with("unbind")));
        assert!(parse_overrides(&out).is_empty());
    }
}
