//! The `tezca-settings` managed override block.
//!
//! `tezca hypr` and `tezca display` persist live tweaks here so they survive
//! `hyprctl reload` and relogin. The block is delimited by two marker comments
//! and holds plain Hyprland config lines: flat `category:name = value` keywords
//! (verified accepted by the 0.55 config parser) and `monitor = …` lines. Every
//! entry carries a stable KEY so re-setting an option replaces its line instead
//! of appending a duplicate. Everything OUTSIDE the block is preserved verbatim.
//!
//! ## Why this lives in `~/.config/tezca/`, not in the repo
//!
//! It used to be written to `conf.d/local.conf`. But `~/.config/hypr` is a symlink
//! into the repo, so every `tezca hypr set` wrote into a **git-tracked file**: the
//! working tree was permanently dirty, a downstream clone could not `git pull`
//! without conflicting on it, and committing published machine-local state
//! (monitor geometry, connector names). Generated state belongs outside the
//! checkout, so the block now lives at `~/.config/tezca/local.conf`, which
//! `hyprland.conf` sources last. `conf.d/local.conf` stays in the repo as the
//! hand-editable stub it was always documented to be — nothing writes to it now.
//!
//! [`ensure_migrated`] moves an existing block across on first use, so an install
//! that predates the split keeps its settings.

use crate::{atomic, repo, term};
use std::fs;
use std::path::PathBuf;

const BEGIN: &str =
    "# >>> tezca-settings managed (auto-generated — edit via `tezca hypr`/settings) >>>";
const END: &str = "# <<< tezca-settings managed <<<";

/// Header written above the block in a freshly created file.
const STUB_HEADER: &str = "\
# ~/.config/tezca/local.conf — generated by `tezca hypr` / `tezca display`.
#
# Machine-local Hyprland overrides, sourced LAST by hyprland.conf so they win.
# The block below is rewritten whenever you change a setting in tezca-settings or
# run `tezca hypr set` / `tezca display set`. Editing it by hand is fine — the keys
# are stable — but expect the tool to reformat it.
#
# For hand-written tweaks you never want touched, use conf.d/local.conf instead:
# it is sourced just before this file, and Tezca never writes to it.
";

/// Where the managed block lives: `~/.config/tezca/local.conf`.
fn path() -> Result<PathBuf, String> {
    Ok(repo::config_home()?.join("tezca").join("local.conf"))
}

/// The pre-split location. Still sourced (for hand edits), never written.
fn legacy_path() -> Result<PathBuf, String> {
    Ok(repo::config_home()?.join("hypr").join("conf.d").join("local.conf"))
}

/// Create the file if absent, so Hyprland's `source` of it never errors on a
/// fresh install. Returns whether it created anything. Called by `tezca link`.
pub fn seed() -> Result<bool, String> {
    let p = path()?;
    if p.exists() {
        return Ok(false);
    }
    atomic::write(&p, STUB_HEADER)?;
    Ok(true)
}

/// Move a pre-split block out of `conf.d/local.conf` into the new home.
///
/// Idempotent and cheap: once the new file exists this is a single `stat`. Runs
/// before every managed read/write, so upgrading needs no explicit step.
pub fn ensure_migrated() -> Result<(), String> {
    let new = path()?;
    if new.exists() {
        return Ok(());
    }
    let Ok(old) = legacy_path() else { return Ok(()) };
    let Ok(text) = fs::read_to_string(&old) else { return Ok(()) };
    if !text.contains(BEGIN) {
        return Ok(());
    }

    let lines = block_lines(&text)?;
    // Write the new home first, then strip the old file — in that order, so an
    // interruption between the two leaves the settings in both places rather
    // than in neither.
    atomic::write(&new, &render(STUB_HEADER, &lines)?)?;
    atomic::write(&old, &render(&text, &[])?)?;
    eprintln!(
        "  {} moved {} managed override(s) out of the repo → {}",
        term::dim("migrated:"),
        lines.len(),
        new.display()
    );
    Ok(())
}

/// The stable identity of a managed line — what we dedup on.
///   `decoration:rounding = 12`   → "decoration:rounding"
///   `monitor = DP-1,3440x1440@165,0x0,1` → "monitor:DP-1"
fn line_key(l: &str) -> Option<String> {
    let t = l.trim();
    if t.is_empty() || t.starts_with('#') {
        return None;
    }
    let (lhs, rhs) = t.split_once('=')?;
    let lhs = lhs.trim();
    if lhs == "monitor" {
        let name = rhs.trim().split(',').next()?.trim();
        if name.is_empty() {
            return None;
        }
        Some(format!("monitor:{name}"))
    } else {
        Some(lhs.to_string())
    }
}

/// Upsert one managed line, keyed by `key`. Creates the block if absent.
pub fn set(key: &str, line: &str) -> Result<(), String> {
    // An entry is one line by construction. A caller that let a newline through
    // would append a directive keyed only by its first line — which `reset` could
    // then never remove. Callers validate their inputs (`crate::validate`); this
    // is the backstop that keeps the invariant local to the module that relies
    // on it.
    if line.contains('\n') || line.contains('\r') {
        return Err(format!("refusing to write a multi-line managed entry: {line:?}"));
    }
    ensure_migrated()?;
    let text = read()?;
    let mut lines = block_lines(&text)?;
    if let Some(slot) = lines.iter_mut().find(|l| line_key(l).as_deref() == Some(key)) {
        *slot = line.to_string();
    } else {
        lines.push(line.to_string());
    }
    write(&text, &lines)
}

/// Remove the managed line with the given key (no-op if absent).
pub fn remove(key: &str) -> Result<(), String> {
    ensure_migrated()?;
    let text = read()?;
    let mut lines = block_lines(&text)?;
    let before = lines.len();
    lines.retain(|l| line_key(l).as_deref() != Some(key));
    if lines.len() == before {
        return Ok(());
    }
    write(&text, &lines)
}

/// Remove every managed line whose key satisfies `pred`. Used by resets
/// (e.g. drop all `decoration:*`/`general:*` keywords but keep `monitor:*`).
pub fn remove_where(pred: impl Fn(&str) -> bool) -> Result<(), String> {
    ensure_migrated()?;
    let text = read()?;
    let mut lines = block_lines(&text)?;
    lines.retain(|l| match line_key(l) {
        Some(k) => !pred(&k),
        None => true,
    });
    write(&text, &lines)
}

/// The keys currently persisted in the managed block.
pub fn keys() -> Vec<String> {
    let _ = ensure_migrated();
    read()
        .and_then(|t| block_lines(&t))
        .unwrap_or_default()
        .iter()
        .filter_map(|l| line_key(l))
        .collect()
}

// --- IO --------------------------------------------------------------------

fn read() -> Result<String, String> {
    Ok(fs::read_to_string(path()?).unwrap_or_default())
}

fn write(text: &str, lines: &[String]) -> Result<(), String> {
    let p = path()?;
    let body = render(text, lines)?;
    atomic::write(&p, &body)
}

// --- pure core (unit-tested) ------------------------------------------------

/// The non-empty, non-marker lines currently inside the managed block.
///
/// Errors on an unterminated block. Previously an unbalanced `BEGIN` — from a
/// truncated write, or a hand-edit that removed the closing marker — left the
/// scanner "inside" for the rest of the file, so the next write silently dropped
/// everything below the marker. Refusing is the only safe response: there is no
/// way to tell where the block was meant to end.
fn block_lines(text: &str) -> Result<Vec<String>, String> {
    let mut out = Vec::new();
    let mut inside = false;
    for l in text.lines() {
        match l.trim() {
            BEGIN => {
                if inside {
                    return Err(unbalanced("a second BEGIN marker before the first was closed"));
                }
                inside = true;
            }
            END => inside = false,
            t if inside && !t.is_empty() && !t.starts_with('#') => out.push(t.to_string()),
            _ => {}
        }
    }
    if inside {
        return Err(unbalanced("the BEGIN marker has no matching END"));
    }
    Ok(out)
}

/// Rewrite `text`: preserve everything outside the block, replace the block with
/// `lines` (dropping it entirely when empty).
fn render(text: &str, lines: &[String]) -> Result<String, String> {
    let mut kept: Vec<&str> = Vec::new();
    let mut inside = false;
    for l in text.lines() {
        match l.trim() {
            BEGIN => {
                if inside {
                    return Err(unbalanced("a second BEGIN marker before the first was closed"));
                }
                inside = true;
            }
            END => inside = false,
            _ if !inside => kept.push(l),
            _ => {}
        }
    }
    if inside {
        return Err(unbalanced("the BEGIN marker has no matching END"));
    }

    // Trim trailing blank lines so we don't accumulate whitespace each write.
    while matches!(kept.last(), Some(s) if s.trim().is_empty()) {
        kept.pop();
    }

    let mut body = kept.join("\n");
    if !lines.is_empty() {
        if !body.is_empty() {
            body.push_str("\n\n");
        }
        body.push_str(BEGIN);
        body.push('\n');
        for l in lines {
            body.push_str(l);
            body.push('\n');
        }
        body.push_str(END);
    }
    body.push('\n');
    Ok(body)
}

fn unbalanced(why: &str) -> String {
    format!(
        "the managed block in local.conf is malformed ({why}).\n  \
         Refusing to rewrite it, because everything below the marker would be lost.\n  \
         Fix it by hand — restore the `{END}` line, or delete the block entirely."
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn v(lines: &[&str]) -> Vec<String> {
        lines.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn reads_only_the_lines_inside_the_block() {
        let text = format!(
            "# a hand-written comment\nmonitor = DP-9, preferred, auto, 1\n\n{BEGIN}\n\
             decoration:rounding = 12\n# a comment inside\n\ngeneral:gaps_in = 3\n{END}\n"
        );
        assert_eq!(
            block_lines(&text).unwrap(),
            v(&["decoration:rounding = 12", "general:gaps_in = 3"])
        );
    }

    #[test]
    fn preserves_everything_outside_the_block() {
        let text =
            format!("# keep me\nmonitor = DP-9, preferred, auto, 1\n{BEGIN}\nold = 1\n{END}\n");
        let out = render(&text, &v(&["new = 2"])).unwrap();
        assert!(out.starts_with("# keep me\nmonitor = DP-9, preferred, auto, 1\n"), "{out}");
        assert!(out.contains("new = 2"));
        assert!(!out.contains("old = 1"));
    }

    #[test]
    fn drops_the_block_entirely_when_nothing_is_left() {
        let text = format!("# keep me\n{BEGIN}\nold = 1\n{END}\n");
        let out = render(&text, &[]).unwrap();
        assert_eq!(out, "# keep me\n");
        assert!(!out.contains(BEGIN));
    }

    #[test]
    fn repeated_writes_are_idempotent_and_do_not_accumulate_blank_lines() {
        let mut text = "# header\n".to_string();
        for _ in 0..5 {
            let lines = block_lines(&text).unwrap();
            text = render(&text, &lines).unwrap();
        }
        assert_eq!(text, "# header\n");

        text = render(&text, &v(&["a = 1"])).unwrap();
        let once = text.clone();
        for _ in 0..5 {
            let lines = block_lines(&text).unwrap();
            text = render(&text, &lines).unwrap();
        }
        assert_eq!(text, once);
    }

    #[test]
    fn refuses_to_rewrite_a_block_with_no_closing_marker() {
        // The regression: `inside` stayed true to EOF, so this trailing user
        // content was silently discarded by the next `tezca hypr set`.
        let text = format!("# header\n{BEGIN}\na = 1\nmonitor = DP-9, preferred, auto, 1\n");
        let e = block_lines(&text).unwrap_err();
        assert!(e.contains("no matching END"), "{e}");
        assert!(render(&text, &v(&["b = 2"])).is_err());
    }

    #[test]
    fn refuses_a_doubled_begin_marker() {
        let text = format!("{BEGIN}\na = 1\n{BEGIN}\nb = 2\n{END}\n");
        assert!(block_lines(&text).is_err());
        assert!(render(&text, &[]).is_err());
    }

    #[test]
    fn keys_a_monitor_line_by_connector_and_a_keyword_by_path() {
        assert_eq!(line_key("decoration:rounding = 12").as_deref(), Some("decoration:rounding"));
        assert_eq!(
            line_key("monitor = DP-1,3440x1440@165,0x0,1").as_deref(),
            Some("monitor:DP-1")
        );
        assert_eq!(line_key("# comment"), None);
        assert_eq!(line_key(""), None);
        assert_eq!(line_key("no equals sign here"), None);
    }

    #[test]
    fn re_setting_a_key_replaces_its_line_instead_of_appending() {
        let text = format!("{BEGIN}\ndecoration:rounding = 12\ngeneral:gaps_in = 3\n{END}\n");
        let mut lines = block_lines(&text).unwrap();
        let (key, new) = ("decoration:rounding", "decoration:rounding = 20");
        if let Some(slot) = lines.iter_mut().find(|l| line_key(l).as_deref() == Some(key)) {
            *slot = new.to_string();
        } else {
            lines.push(new.to_string());
        }
        assert_eq!(lines, v(&["decoration:rounding = 20", "general:gaps_in = 3"]));
    }

    #[test]
    fn migration_moves_the_block_and_leaves_the_hand_written_stub_behind() {
        // What `ensure_migrated` does to each of the two files, without touching
        // the real filesystem.
        let legacy = format!(
            "# conf.d/local.conf — machine-local overrides.\n#\n#   monitor = DP-3, …\n\n\
             {BEGIN}\ndecoration:blur:size = 5\ngeneral:gaps_in = 3\n{END}\n"
        );
        let moved = block_lines(&legacy).unwrap();
        assert_eq!(moved, v(&["decoration:blur:size = 5", "general:gaps_in = 3"]));

        let new_file = render(STUB_HEADER, &moved).unwrap();
        assert!(new_file.contains("decoration:blur:size = 5"));
        assert!(new_file.contains("# ~/.config/tezca/local.conf"));

        let stripped = render(&legacy, &[]).unwrap();
        assert!(!stripped.contains(BEGIN), "the block must be gone from the old file");
        assert!(stripped.contains("# conf.d/local.conf"), "the stub must survive");
        assert!(stripped.contains("#   monitor = DP-3, …"));
    }
}
