//! The `tezca-settings` generated override store.
//!
//! `tezca hypr` and `tezca display` persist live tweaks here so they survive
//! `hyprctl reload` and relogin. The store is `~/.config/tezca/overrides.lua`,
//! which `hyprland.lua` applies LAST (through `util.apply_overrides`), so it wins
//! over every shipped fragment.
//!
//! ## Why this is a data table and not generated config code
//!
//! Under hyprlang this was a block of real config lines fenced by two marker
//! comments inside a larger hand-editable file, which forced three awkward jobs:
//! find the fence, preserve everything outside it, and refuse to write when the
//! fence was damaged (a truncated write used to silently eat the rest of the
//! file). The Lua port makes all three disappear. Tezca owns this file end to
//! end, so it is simply rewritten whole; and its contents are *data* —
//!
//!     return { ["decoration:rounding"] = 14, monitors = { … } }
//!
//! — never executable config. That matters because a Lua config error is not a
//! logged warning like hyprlang's, it drops the session into emergency mode with
//! a single keybind. Generated code could do that; a table that
//! `util.apply_overrides` validates key-by-key cannot: a key Hyprland no longer
//! recognises after an upgrade is dropped with a log line and the rest still
//! applies.
//!
//! Keys are stored in Hyprland's own option-path spelling (`decoration:rounding`,
//! `general:col.active_border`) — exactly what `tezca hypr set`, `hyprctl
//! getoption` and the Settings sliders speak. `util.nest` splits on both `:` and
//! `.`, so nothing has to be translated in either direction and there is no
//! round-trip to get wrong.
//!
//! ## Why it lives in `~/.config/tezca/`, not in the repo
//!
//! `~/.config/hypr` is a symlink into the repo, so writing generated state there
//! left the working tree permanently dirty, blocked `git pull` in a downstream
//! clone, and published machine-local state (monitor geometry, connector names).
//! [`ensure_migrated`] carries an older install's settings across — from the
//! pre-Lua `~/.config/tezca/local.conf` block, and from the even older
//! `conf.d/local.conf` one before that — so upgrading needs no explicit step.

use crate::{atomic, repo, term};
use std::fs;
use std::path::PathBuf;

/// Markers used by the two pre-Lua layouts we migrate away from.
const LEGACY_BEGIN: &str =
    "# >>> tezca-settings managed (auto-generated — edit via `tezca hypr`/settings) >>>";
const LEGACY_END: &str = "# <<< tezca-settings managed <<<";

const HEADER: &str = "\
-- ~/.config/tezca/overrides.lua — generated by `tezca hypr` / `tezca display`.
--
-- Machine-local Hyprland overrides, applied LAST by hyprland.lua so they win.
-- Rewritten in full whenever you change a setting in tezca-settings or run
-- `tezca hypr set` / `tezca display set`. Tezca owns this file: hand edits
-- survive only if they keep the shape below, and will be reformatted.
--
-- This is DATA, not config code. It must stay a bare `return { … }` table:
-- option keys spelled exactly as `hyprctl getoption` spells them, and an
-- optional `monitors` array. hyprland.lua feeds it through
-- conf.d/util.lua:apply_overrides, which validates each entry and drops only the
-- ones Hyprland rejects — so a stale key cannot cost you the session.
--
-- For hand-written tweaks you never want touched, use conf.d/local.lua instead:
-- it is loaded just before this file, and Tezca never writes to it.
";

/// One `hl.monitor` entry. Fields are kept as strings because they are echoed
/// straight back to Hyprland; only `scale` is emitted unquoted when numeric.
///
/// The optional fields below are emitted only when set, so a monitor configured
/// the way every monitor was configured before they existed still renders
/// byte-for-byte identically (there is a test for exactly that). `hl.monitor`
/// validates its field names strictly — an unknown key aborts the call with
/// `hl.monitor: unknown field 'x'` — so this list was established by probing the
/// running compositor rather than from documentation. Note there is no `enabled`
/// field: a monitor is switched off with `disabled = true`.
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Monitor {
    pub output: String,
    pub mode: String,
    pub position: String,
    pub scale: String,
    /// Empty or "0" means "don't emit a transform".
    pub transform: String,
    /// "" (inherit the global `misc:vrr`) | "0" off | "1" on | "2" fullscreen-only.
    pub vrr: String,
    /// "" (inherit) | "8" | "10".
    pub bitdepth: String,
    /// "" (none) | a connector name to mirror.
    pub mirror: String,
    /// True when the output is switched off entirely.
    pub disabled: bool,
}

/// The whole generated store, in memory.
#[derive(Clone, Debug, Default, PartialEq)]
struct Store {
    /// (option path, Lua value literal), insertion-ordered for a stable file.
    options: Vec<(String, String)>,
    monitors: Vec<Monitor>,
}

fn path() -> Result<PathBuf, String> {
    Ok(repo::config_home()?.join("tezca").join("overrides.lua"))
}

/// The pre-Lua store. Still read once by [`ensure_migrated`], never written.
fn legacy_path() -> Result<PathBuf, String> {
    Ok(repo::config_home()?.join("tezca").join("local.conf"))
}

/// The pre-split store, older still.
fn ancient_path() -> Result<PathBuf, String> {
    Ok(repo::config_home()?.join("hypr").join("conf.d").join("local.conf"))
}

/// Create the file if absent, so hyprland.lua always finds something. Returns
/// whether it created anything. Called by `tezca link`.
pub fn seed() -> Result<bool, String> {
    let p = path()?;
    if p.exists() {
        return Ok(false);
    }
    atomic::write(&p, &render(&Store::default()))?;
    Ok(true)
}

/// Carry a pre-Lua managed block into `overrides.lua`.
///
/// Idempotent and cheap: once the new file exists this is a single `stat`. Runs
/// before every read/write, so upgrading needs no explicit step.
pub fn ensure_migrated() -> Result<(), String> {
    let new = path()?;
    if new.exists() {
        return Ok(());
    }

    for old in [legacy_path()?, ancient_path()?] {
        let Ok(text) = fs::read_to_string(&old) else { continue };
        if !text.contains(LEGACY_BEGIN) {
            continue;
        }
        let store = parse_legacy_block(&text)?;
        let carried = store.options.len() + store.monitors.len();

        // Write the new home first, then strip the old block — in that order, so
        // an interruption between the two leaves the settings in both places
        // rather than in neither.
        atomic::write(&new, &render(&store))?;
        atomic::write(&old, &strip_legacy_block(&text)?)?;
        eprintln!(
            "  {} carried {carried} override(s) from {} → {}",
            term::dim("migrated:"),
            old.display(),
            new.display()
        );
        return Ok(());
    }
    Ok(())
}

// --- public API -------------------------------------------------------------

/// Upsert one option override, keyed by its Hyprland option path.
pub fn set(key: &str, value: &str) -> Result<(), String> {
    // A newline would let a caller smuggle extra table entries — or an entire
    // `}` — into a generated file that is then executed as Lua. Callers validate
    // their inputs (`crate::validate`); this is the backstop that keeps the
    // invariant local to the module that relies on it.
    if key.contains(['\n', '\r']) || value.contains(['\n', '\r']) {
        return Err(format!("refusing to write a multi-line override: {key:?} = {value:?}"));
    }
    let mut store = read()?;
    let lit = lua_value(value);
    match store.options.iter_mut().find(|(k, _)| k == key) {
        Some(slot) => slot.1 = lit,
        None => store.options.push((key.to_string(), lit)),
    }
    write(&store)
}

/// Every persisted monitor override, in file order.
pub fn monitors() -> Vec<Monitor> {
    read().map(|s| s.monitors).unwrap_or_default()
}

/// Upsert one monitor override, keyed by its connector name.
pub fn set_monitor(m: Monitor) -> Result<(), String> {
    if [&m.output, &m.mode, &m.position, &m.scale, &m.transform, &m.vrr, &m.bitdepth, &m.mirror]
        .iter()
        .any(|f| f.contains(['\n', '\r', '"', '\\']))
    {
        return Err(format!("refusing to write a malformed monitor override: {m:?}"));
    }
    let mut store = read()?;
    match store.monitors.iter_mut().find(|e| e.output == m.output) {
        Some(slot) => *slot = m,
        None => store.monitors.push(m),
    }
    write(&store)
}

/// Remove the override with the given key (no-op if absent). `monitor:<NAME>`
/// addresses a monitor entry; anything else is an option path.
pub fn remove(key: &str) -> Result<(), String> {
    let mut store = read()?;
    let before = store.options.len() + store.monitors.len();
    match key.strip_prefix("monitor:") {
        Some(name) => store.monitors.retain(|m| m.output != name),
        None => store.options.retain(|(k, _)| k != key),
    }
    if store.options.len() + store.monitors.len() == before {
        return Ok(());
    }
    write(&store)
}

/// Remove every override whose key satisfies `pred`. Used by resets (e.g. drop
/// all `decoration:*`/`general:*` options but keep `monitor:*`).
pub fn remove_where(pred: impl Fn(&str) -> bool) -> Result<(), String> {
    let mut store = read()?;
    store.options.retain(|(k, _)| !pred(k));
    store.monitors.retain(|m| !pred(&format!("monitor:{}", m.output)));
    write(&store)
}

/// The keys currently persisted, options first then `monitor:<NAME>` entries.
pub fn keys() -> Vec<String> {
    let store = read().unwrap_or_default();
    store
        .options
        .iter()
        .map(|(k, _)| k.clone())
        .chain(store.monitors.iter().map(|m| format!("monitor:{}", m.output)))
        .collect()
}

// --- IO ---------------------------------------------------------------------

fn read() -> Result<Store, String> {
    ensure_migrated()?;
    let text = fs::read_to_string(path()?).unwrap_or_default();
    parse(&text)
}

fn write(store: &Store) -> Result<(), String> {
    atomic::write(&path()?, &render(store))
}

// --- pure core (unit-tested) ------------------------------------------------

/// Format a user-supplied value as a Lua literal.
///
/// Numbers and booleans stay bare so Hyprland receives the type it expects for
/// an int/float/bool option; everything else is a quoted string, which is what
/// gradients and colors (`rgba(…)`, `… 45deg`) need.
///
/// Shared with [`crate::hypr`], which builds the `hl.config` snippet for the
/// live-apply half of the same `set`. The stored value and the applied value
/// must be spelled identically or a reload would visibly change the setting.
pub(crate) fn lua_value(v: &str) -> String {
    let t = v.trim();
    if t == "true" || t == "false" {
        return t.to_string();
    }
    // Reject the exotic float spellings `parse::<f64>` accepts — "inf", "NaN"
    // and hex — so they round-trip as strings rather than as bare Lua words that
    // would not even parse.
    let numeric = !t.is_empty()
        && t.parse::<f64>().is_ok()
        && t.chars().all(|c| c.is_ascii_digit() || "+-.eE".contains(c));
    if numeric {
        return t.to_string();
    }
    format!("\"{}\"", t.replace('\\', "\\\\").replace('"', "\\\""))
}

/// The `hl.monitor` field list for `m`, without the enclosing braces.
///
/// Shared by the generated override file ([`render`]) and the live-apply snippet
/// (`hypr::lua_monitor_call`). These two must spell a monitor **identically** —
/// they are the same setting applied now and applied again at the next reload, so
/// any divergence shows up as the display visibly changing when you reload. They
/// were separate copies of this logic until the optional fields below made that a
/// standing bug waiting to happen.
///
/// Optional fields are emitted only when set: a monitor carrying none of them
/// renders exactly as it did before they existed.
pub(crate) fn monitor_fields(m: &Monitor) -> String {
    let mut s = format!(
        "output = \"{}\", mode = \"{}\", position = \"{}\", scale = {}",
        m.output,
        m.mode,
        m.position,
        lua_value(&m.scale)
    );
    if !m.transform.is_empty() && m.transform != "0" {
        s.push_str(&format!(", transform = {}", lua_value(&m.transform)));
    }
    if !m.vrr.is_empty() {
        s.push_str(&format!(", vrr = {}", lua_value(&m.vrr)));
    }
    if !m.bitdepth.is_empty() {
        s.push_str(&format!(", bitdepth = {}", lua_value(&m.bitdepth)));
    }
    if !m.mirror.is_empty() {
        s.push_str(&format!(", mirror = {}", lua_value(&m.mirror)));
    }
    if m.disabled {
        s.push_str(", disabled = true");
    }
    s
}

/// Recover the value a caller originally passed from its Lua literal.
fn unlua_value(lit: &str) -> String {
    let t = lit.trim();
    match t.strip_prefix('"').and_then(|s| s.strip_suffix('"')) {
        Some(inner) => inner.replace("\\\"", "\"").replace("\\\\", "\\"),
        None => t.to_string(),
    }
}

fn render(store: &Store) -> String {
    let mut s = String::from(HEADER);
    s.push_str("\nreturn {\n");

    if !store.options.is_empty() {
        // Pad the whole `["key"]` token, never inside the brackets: alignment
        // spaces placed before the `]` separate the closing quote from it, and
        // the reader keys on the `"]` pair — which silently dropped every key
        // that was not the longest one.
        let width = store.options.iter().map(|(k, _)| k.len()).max().unwrap_or(0) + 4;
        for (k, lit) in &store.options {
            s.push_str(&format!("    {:<width$} = {lit},\n", format!("[\"{k}\"]")));
        }
    }

    if !store.monitors.is_empty() {
        if !store.options.is_empty() {
            s.push('\n');
        }
        s.push_str("    monitors = {\n");
        for m in &store.monitors {
            s.push_str(&format!("        {{ {} }},\n", monitor_fields(m)));
        }
        s.push_str("    },\n");
    }

    s.push_str("}\n");
    s
}

/// Read back the restricted subset [`render`] emits.
///
/// This is deliberately a line scanner and not a Lua parser: the only files it
/// ever sees are ones we wrote, so the grammar it must accept is exactly the one
/// above. Anything it does not recognise is ignored rather than guessed at.
fn parse(text: &str) -> Result<Store, String> {
    let mut store = Store::default();
    let mut in_monitors = false;

    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with("--") {
            continue;
        }
        if line.starts_with("monitors") {
            in_monitors = true;
            continue;
        }
        if in_monitors {
            if line.starts_with('}') {
                in_monitors = false;
                continue;
            }
            if let Some(m) = parse_monitor_entry(line) {
                store.monitors.push(m);
            }
            continue;
        }
        // ["decoration:rounding"] = 14,
        if let Some(rest) = line.strip_prefix("[\"") {
            let Some((key, after)) = rest.split_once("\"]") else { continue };
            let Some((_, val)) = after.split_once('=') else { continue };
            let lit = val.trim().trim_end_matches(',').trim();
            if !key.is_empty() && !lit.is_empty() {
                store.options.push((key.to_string(), lit.to_string()));
            }
        }
    }
    Ok(store)
}

/// Parse one rendered `{ output = …, … }` entry. Shared with the display-profile
/// store, which uses the same entry grammar.
pub(crate) fn parse_monitor_entry(line: &str) -> Option<Monitor> {
    let inner = line.trim().trim_start_matches('{').trim_end_matches(',').trim_end_matches('}');
    let mut m = Monitor::default();
    for field in inner.split(',') {
        let Some((k, v)) = field.split_once('=') else { continue };
        let v = unlua_value(v.trim());
        match k.trim() {
            "output" => m.output = v,
            "mode" => m.mode = v,
            "position" => m.position = v,
            "scale" => m.scale = v,
            "transform" => m.transform = v,
            "vrr" => m.vrr = v,
            "bitdepth" => m.bitdepth = v,
            "mirror" => m.mirror = v,
            "disabled" => m.disabled = v == "true",
            _ => {}
        }
    }
    (!m.output.is_empty()).then_some(m)
}

// --- migration off the hyprlang block ---------------------------------------

/// Read a pre-Lua managed block (`k = v` and `monitor = …` lines) into a Store.
fn parse_legacy_block(text: &str) -> Result<Store, String> {
    let mut store = Store::default();
    let mut inside = false;
    for l in text.lines() {
        match l.trim() {
            LEGACY_BEGIN => {
                if inside {
                    return Err(unbalanced("a second BEGIN marker before the first was closed"));
                }
                inside = true;
            }
            LEGACY_END => inside = false,
            t if inside && !t.is_empty() && !t.starts_with('#') => {
                let Some((lhs, rhs)) = t.split_once('=') else { continue };
                let (lhs, rhs) = (lhs.trim(), rhs.trim());
                if lhs == "monitor" {
                    // monitor = DP-1,3440x1440@165,0x0,1[,transform,N]
                    let f: Vec<&str> = rhs.split(',').map(str::trim).collect();
                    if f.first().is_some_and(|n| !n.is_empty()) {
                        store.monitors.push(Monitor {
                            output: f[0].to_string(),
                            mode: f.get(1).unwrap_or(&"preferred").to_string(),
                            position: f.get(2).unwrap_or(&"auto").to_string(),
                            scale: f.get(3).unwrap_or(&"1").to_string(),
                            transform: match f.iter().position(|x| *x == "transform") {
                                Some(i) => f.get(i + 1).unwrap_or(&"").to_string(),
                                None => String::new(),
                            },
                            // The hyprlang block predates all of these; a
                            // migrated monitor simply has none of them set.
                            ..Default::default()
                        });
                    }
                } else if !lhs.is_empty() {
                    store.options.push((lhs.to_string(), lua_value(rhs)));
                }
            }
            _ => {}
        }
    }
    if inside {
        return Err(unbalanced("the BEGIN marker has no matching END"));
    }
    Ok(store)
}

/// Return `text` with the managed block removed, everything else verbatim.
fn strip_legacy_block(text: &str) -> Result<String, String> {
    let mut kept: Vec<&str> = Vec::new();
    let mut inside = false;
    for l in text.lines() {
        match l.trim() {
            LEGACY_BEGIN => {
                if inside {
                    return Err(unbalanced("a second BEGIN marker before the first was closed"));
                }
                inside = true;
            }
            LEGACY_END => inside = false,
            _ if !inside => kept.push(l),
            _ => {}
        }
    }
    if inside {
        return Err(unbalanced("the BEGIN marker has no matching END"));
    }
    while matches!(kept.last(), Some(s) if s.trim().is_empty()) {
        kept.pop();
    }
    let mut body = kept.join("\n");
    body.push('\n');
    Ok(body)
}

fn unbalanced(why: &str) -> String {
    format!(
        "the managed block in the pre-Lua local.conf is malformed ({why}).\n  \
         Refusing to migrate it, because everything below the marker would be lost.\n  \
         Fix it by hand — restore the `{LEGACY_END}` line, or delete the block entirely."
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mon(output: &str, mode: &str) -> Monitor {
        Monitor {
            output: output.into(),
            mode: mode.into(),
            position: "0x0".into(),
            scale: "1".into(),
            ..Default::default()
        }
    }

    #[test]
    fn a_plain_monitor_still_renders_exactly_as_it_did_before_the_advanced_fields() {
        // The optional fields (vrr/bitdepth/mirror/disabled) must be invisible
        // until used: an overrides.lua written by the previous version has to
        // keep round-tripping, and upgrading must not rewrite anyone's file.
        assert_eq!(
            monitor_fields(&mon("DP-1", "3440x1440@165")),
            r#"output = "DP-1", mode = "3440x1440@165", position = "0x0", scale = 1"#
        );
    }

    #[test]
    fn round_trips_every_advanced_monitor_field() {
        let m = Monitor {
            output: "DP-3".into(),
            mode: "2560x1440@165".into(),
            position: "3440x0".into(),
            scale: "1.25".into(),
            transform: "3".into(),
            vrr: "2".into(),
            bitdepth: "10".into(),
            mirror: "DP-1".into(),
            disabled: true,
        };
        let store = Store { options: vec![], monitors: vec![m.clone()] };
        assert_eq!(parse(&render(&store)).unwrap(), store);
        // …and rewriting stays a fixed point with the new fields present.
        assert_eq!(render(&parse(&render(&store)).unwrap()), render(&store));
    }

    #[test]
    fn reads_a_file_written_before_the_advanced_fields_existed() {
        // Forward-compatibility, spelled out as a literal rather than generated:
        // this is exactly what is sitting in users' ~/.config/tezca/overrides.lua.
        let old = "\nreturn {\n    monitors = {\n        \
                   { output = \"DP-1\", mode = \"3440x1440@165\", position = \"0x0\", scale = 1 },\n\
                   \x20   },\n}\n";
        let store = parse(old).unwrap();
        assert_eq!(store.monitors.len(), 1);
        assert_eq!(store.monitors[0], mon("DP-1", "3440x1440@165"));
        assert!(store.monitors[0].vrr.is_empty());
        assert!(!store.monitors[0].disabled);
    }

    #[test]
    fn renders_a_table_that_is_valid_lua_and_parses_back_identically() {
        let store = Store {
            options: vec![
                ("decoration:rounding".into(), "14".into()),
                ("general:col.active_border".into(), "\"rgba(3FB8AFff)\"".into()),
            ],
            monitors: vec![mon("DP-1", "3440x1440@165")],
        };
        let text = render(&store);
        assert!(text.contains("return {"));
        assert_eq!(parse(&text).unwrap(), store);
    }

    #[test]
    fn round_trips_an_empty_store_without_accumulating_anything() {
        let text = render(&Store::default());
        assert_eq!(parse(&text).unwrap(), Store::default());
        // Rewriting is a fixed point — the file must not grow on repeated writes.
        assert_eq!(render(&parse(&text).unwrap()), text);
    }

    #[test]
    fn types_values_so_hyprland_gets_int_float_bool_or_string() {
        assert_eq!(lua_value("14"), "14");
        assert_eq!(lua_value("0.98"), "0.98");
        assert_eq!(lua_value("-40"), "-40");
        assert_eq!(lua_value("true"), "true");
        assert_eq!(lua_value("rgba(3FB8AFff)"), "\"rgba(3FB8AFff)\"");
        assert_eq!(lua_value("$tz_accent $tz_accent_dim 45deg"), "\"$tz_accent $tz_accent_dim 45deg\"");
        // `inf`/`NaN` parse as f64 but are not Lua number literals we want bare.
        assert_eq!(lua_value("inf"), "\"inf\"");
        assert_eq!(lua_value("NaN"), "\"NaN\"");
    }

    #[test]
    fn escapes_quotes_and_backslashes_so_generated_lua_cannot_break_out() {
        let lit = lua_value(r#"say "hi" \ bye"#);
        assert_eq!(lit, r#""say \"hi\" \\ bye""#);
        assert_eq!(unlua_value(&lit), r#"say "hi" \ bye"#);
    }

    #[test]
    fn re_setting_a_key_replaces_its_entry_instead_of_appending() {
        let mut store = Store {
            options: vec![("decoration:rounding".into(), "12".into())],
            monitors: vec![],
        };
        let key = "decoration:rounding";
        match store.options.iter_mut().find(|(k, _)| k == key) {
            Some(slot) => slot.1 = "20".into(),
            None => store.options.push((key.into(), "20".into())),
        }
        assert_eq!(store.options, vec![("decoration:rounding".into(), "20".to_string())]);
    }

    #[test]
    fn migrates_a_hyprlang_block_into_typed_table_entries() {
        let legacy = format!(
            "# ~/.config/tezca/local.conf\n\n{LEGACY_BEGIN}\n\
             decoration:rounding = 12\ngeneral:gaps_in = 3\n\
             monitor = DP-1,3440x1440@165,0x0,1\n\
             monitor = DP-3,2560x1440@165,3440x0,1,transform,1\n{LEGACY_END}\n"
        );
        let store = parse_legacy_block(&legacy).unwrap();
        assert_eq!(
            store.options,
            vec![
                ("decoration:rounding".to_string(), "12".to_string()),
                ("general:gaps_in".to_string(), "3".to_string()),
            ]
        );
        assert_eq!(store.monitors.len(), 2);
        assert_eq!(store.monitors[1].position, "3440x0");
        assert_eq!(store.monitors[1].transform, "1");
        // and the migrated form survives a render/parse round trip
        assert_eq!(parse(&render(&store)).unwrap(), store);
    }

    #[test]
    fn stripping_the_legacy_block_preserves_everything_around_it() {
        let legacy =
            format!("# keep me\n# and me\n{LEGACY_BEGIN}\ndecoration:rounding = 12\n{LEGACY_END}\n");
        let out = strip_legacy_block(&legacy).unwrap();
        assert_eq!(out, "# keep me\n# and me\n");
        assert!(!out.contains(LEGACY_BEGIN));
    }

    #[test]
    fn refuses_to_migrate_a_block_with_no_closing_marker() {
        // The old regression: `inside` stayed true to EOF, so trailing user
        // content was silently discarded. Migration must refuse, not guess.
        let text = format!("# header\n{LEGACY_BEGIN}\na = 1\nmonitor = DP-9,preferred,auto,1\n");
        let e = parse_legacy_block(&text).unwrap_err();
        assert!(e.contains("no matching END"), "{e}");
        assert!(strip_legacy_block(&text).is_err());
    }

    #[test]
    fn ignores_comments_and_unrecognised_lines_when_parsing() {
        let text = "-- a comment\nreturn {\n    [\"decoration:rounding\"] = 14,\n\
                    -- another\n    something_else = 5,\n}\n";
        let store = parse(text).unwrap();
        assert_eq!(store.options, vec![("decoration:rounding".to_string(), "14".to_string())]);
    }
}

